### ISSUE TITLE
[Bug] if compile error when running lucky db.migrate.one,  the migration status get migrated unexpectly.

### ISSUE THREAD

**Issue by zw963** [luckyframework/avram#1032]
I meet this issue several times recent days, let me explain by an example:

###  Then i running migration use `lucky db.migrate.one, i get following error because write code wrong.

```
 ╰─ $ lucky db.migrate.one
Showing last frame. Use --error-trace for full trace.

In db/migrations/20240427102500_foo.cr:5:20

 5 | University.update!(university, batch_level: University::BatchNumber::LevelOne_A.value)
                ^------
Error: undefined method 'update!' for University.class
```

###  I fixed that bug, run it again, but, get error again.

```
Showing last frame. Use --error-trace for full trace.

In db/migrations/20240427102500_foo.cr:10:7

 10 | make_required :batch_level
      ^------------
Error: wrong number of arguments for 'UpdateBatchLevelData::V20240427102500#make_required' (given 1, expected 2)
```

This time because i write code like this: (okay, i thought it should support usage like this, this should  i will create a new issue for this)

```cr
alter table_for(University) do
      remove :batch_number
      make_required :batch_level
    end
```
### I refactor above code like this, run again, get new error 

```
    make_required table_for(University), :batch_level
    remove table_for(University), :batch_number

```

Okay, i consider we should support usage like this this too, (same as above, will create a new issue)

```
 ╰─ $ 1  lucky db.migrate.one
Showing last frame. Use --error-trace for full trace.

In db/migrations/20240427102500_update_batch_level_data.cr:10:5

 10 | remove table_for(University), :batch_number
      ^-----
Error: undefined method 'remove' for UpdateBatchLevelData::V20240427102500
```

### Finally, i fixed my migration use following code, run it again.

```cr
    make_required table_for(University), :batch_level
    alter table_for(University) do
      remove :batch_number
    end
```

But, the result is `Did not migrate anything because there are no pending migrations.`

Check the `lucky db.migrations.status`,  the last one migrated is foo.

```
║ Foo:V20240427102500            | Migrated ║
```

But the db still keep the old status, if this is true, i consider it is a serious issue, it cause the inconsistent state between data and migration.

Thanks

**Comment by zw963** [comment]
Hi, i guess why this issue happen.

I added following code into my config/database.yml

```cr
if !LuckyEnv.task?
  Avram::Migrator::Runner.new.run_pending_migrations
end
```

I thought it should never run when start server use `lucky dev`, because i thought
lucky env is a task, right? but this not true obviously.

so, the migration file get migrate immediately when i generating it use bin/lucky.gen.migration ...

So, the new issue is, how to check current server is running from `lucky dev`? i consider only check $LUCKY_DEV == development is not enough for my case, i just don't want lucky dev run my migration, but, it should be running if i run `shards build` or `lucky db.migrate.one`.

Thanks

**Comment by jwoertink** [comment]
Maybe you can use a compile `env` for this case?

```
# config/database.cr
{% if env("MIGRATE") %}
Avram::Migrator::Runner.new.run_pending_migrations
{% end %}
```

`MIGRATE=true lucky db.migrate.one`

**Comment by zw963** [comment]
> Maybe you can use a compile `env` for this case?
> 
> ```
> # config/database.cr
> {% if env("MIGRATE") %}
> Avram::Migrator::Runner.new.run_pending_migrations
> {% end %}
> ```
> 
> `MIGRATE=true lucky db.migrate.one`

I consider this is not correct,, whatever whether env MIGRATE was set, db.migrate.one always run pending migration.

For now, i change to run pending migrate only in production

```cr
if !LuckyEnv.task? && LuckyEnv.production?
  Avram::Migrator::Runner.new.run_pending_migrations
end
```

But, i still prefer to check if running with `lucky dev`,  anyway, i consider unless running with `lucky dev`, other cases run migration automatically is always a good idea?

**Comment by jwoertink** [comment]
I really think the better option is to use `env()` to specify when you want to control a specific task.

```
# does not run migration
lucky dev

# runs migration
MIGRATE=true lucky dev
```
