### ISSUE TITLE
Remove before callbacks

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/avram#11]
Currently, when forms are saved methods are called in this order:

* **prepare**
* _validation_
* **before_save**
* **before_create** / **before_update**
* _triggering method eg. save, create, or update_
* **after_save**
* **after_create** / **after_update**

**Bold** methods are methods that users can hook into.

There are currently no use cases we can think of for `before_*` callbacks because that method is called _after_ the form is known to be valid.

The thought is, what if we just get rid of them, and add them back if there someone can present a solid use case for them.

## Alternatives

* Remove _prepare_ and move the `before_*` callbacks to they happen before validation
* Remove callbacks and create blocks inside the prepare method to distinguish between create/update steps:
```cr
def prepare
  # validations
  on_create do
    # set token
  end
end
```
* Remove callbacks and have separate `prepare_for_create/update` methods

**Comment by jwoertink** [comment]
Now that this is completely refactored, and we only have the [3 callback](https://www.luckyframework.org/guides/database/validating-saving#callbacks), is this issue still relevant?

**Comment by paulcsmith** [comment]
Nice catch. Can be closed :)
