### ISSUE TITLE
Add table_for(Model) to migrations

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#120]
This will return the table name. e.g. `table_for(User)` -> `:users`

Which can then be used in migrations and the migration generator

`create table_for(User) do/end`. This would work in tandem with the `table` inference in models so they always match up correctly

**Comment by paulcsmith** [comment]
@jwoertink Not sure what you want to work on next but this could be a cool one to add. That way generators can use this and leave out the table name in the `table` macro. Could be kinda cool

**Comment by jwoertink** [comment]
Actually added in via https://github.com/luckyframework/avram/pull/127
