### ISSUE TITLE
Migrate/rollback to specific version

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#125]
https://gitter.im/luckyframework/Lobby?at=5d1b5eda6658420b1cdd4eee

- [x] `lucky db.rollback_to {migration timestamp}` #133 
- [ ] `lucky db.rollback|migrate {migration timestamp}` will migrate or rollback just the specific migration
- [ ] `lucky db.migrate_to {migration timestamp}`

**Comment by KCErb** [comment]
I'm working on the `rollback_to` part of this at the moment. If I can manage a PR for it in a reasonable time frame, I may tacked the other ones as well.

**Comment by grepsedawk** [comment]
I think this is complete

**Comment by jwoertink** [comment]
Yeah, we can close this out. Good catch 👍
