### ISSUE TITLE
Add lucky db.migrations.status

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#126]
Prints the migration name, timestamp, and whether it has been migrated or not. Can probably use the shell-table shard like we do in Lucky for the route helper: https://github.com/luckyframework/lucky/blob/32db2b499227541ab43b5927bf88e1b95a3e53d8/tasks/routes.cr#L9-L17

**Comment by smadeja** [comment]
Looks like this can be closed.

**Comment by paulcsmith** [comment]
Ah yes thank you!
