### ISSUE TITLE
`undefined constant` error for association defition

### ISSUE THREAD

**Issue by sdzyba** [luckyframework/avram#13]
Crystal version: 0.25.1
LuckyRecord version: 0.6.0

When two models `A` and `B` are defined in the project and model `B` is associated to `A` like so:
```
table :a do
  ...
  belongs_to b : B
end
```
user would get a `undefined constant B` error.

My guess is that model files are read in alphabetical order and while parsing model `A` the required model `B` is not loaded yet.

Workaround: add `require "./b"` at the top of model `A` definition file.

**Comment by jwoertink** [comment]
I need confirmation, but I'm pretty sure this is no longer an issue.

**Comment by paulcsmith** [comment]
Yeah I think this is fixed too!

**Comment by jwoertink** [comment]
@sdzyba if you still run in to this issue, please feel free to re-open.
