### ISSUE TITLE
Inferred table names on namespaced models

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#143]
Right now a normal model would look like

```crystal
class User < BaseModel
  table do
  end
end
```

This would use [this function](https://github.com/luckyframework/avram/blob/master/src/run_macros/infer_table_name.cr) to infer the table name to `users`.

Now if you decide to namespace your models in the case of a 3rd party shard that wanted to add in a custom model, or maybe you're re-organizing your project in to a new structure, you may define this:

```crystal
module Papertrail
  class Ledger < BaseModel
    table do
    end
  end
end
```

Your inferred table name would be `papertrail::ledgers`. I've never tried to create a table name like that in postgres, but I assume it wouldn't work. 

We currently have [this file](https://github.com/luckyframework/avram/blob/master/src/avram/table_for.cr) which could handle stripping out the namespaces by making the assumption that `A::B::C::D` you want a table for `D`.

### Temp fix

For anyone that runs in to this (for now), just specify your table name directly.

```crystal
module Papertrail
  class Ledger < BaseModel
    table :ledgers do
    end
  end
end
```

**Comment by paulcsmith** [comment]
Good point! I'm thinking we replace those `::` with underscores by default. That is easy to do inside the macro or in the run_macro for table name inference

**Comment by jwoertink** [comment]
Looks like there's another issue with this. On [this line](https://github.com/luckyframework/avram/blob/master/src/avram/associations/has_many.cr#L9) when your model is namespaced, you'll end up getting something like this:

```crystal
define_has_many_lazy_loading(sheets, Sheet, papertrail::ledger_id, nil)
define_has_many_base_query(sheets, Sheet, papertrail::ledger_id, nil)
```

**Comment by jwoertink** [comment]
found another one: When you use a `where_` association query, it types the `assoc_query` as a [global scope model](https://github.com/luckyframework/avram/blob/master/src/avram/base_query_template.cr#L88), but if you're in a namespace, then that model won't exist.

You'll end up getting an error like `undefined constant ::NamespacedModel::BaseQuery` as where it should be `Namespace::NamespacedMode::BaseQuery`, or just `NamespacedMode::BaseQuery`.
