### ISSUE TITLE
Found a typo

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#148]
[Float64Convertor](https://github.com/luckyframework/avram/blob/master/src/avram/model.cr#L152) is not spelled the same as [Float64Converter](https://github.com/luckyframework/avram/blob/master/src/avram/model.cr#L162)

 and grepping for the first one and only getting 1 result sent me on a wild goose chase only to find it a few lines later 😂

**Comment by jwoertink** [comment]
Actually found another [typo](https://github.com/luckyframework/avram/blob/master/src/avram/model.cr#L152). The key here should be [converter](https://github.com/crystal-lang/crystal-db/blob/f14abc19fdb71bc5a873fbda7955e35e80a61596/src/db/mapping.cr#L111). My guess is this doesn't even work. 🤣

**Comment by paulcsmith** [comment]
I believe you are right :) I  guess we should just remove it then haha
