### ISSUE TITLE
Clarify when you're working on an association query versus associations

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#162]
It can be confusing whether you are working with an association query or the association itself:

```crystal
UserQuery.new
  .join_tasks
  # Here is the problematic line
  .tasks(&.completed(true))
  .first
  .tasks
```

Notice the method name `tasks` is the same, but returns something different depending on whether it is called on the query or on the model. This makes sense, but I think we can  make it clearer.

## ~Proposed solution~ Decision made below

Add a prefix or suffix to the query method. 

* `{association}_query`
* `where_{association}`

```crystal
UserQuery.new
  .join_tasks
  # Here is the example of the change
  .where_tasks(&.completed(true))
  .first
  .tasks
```

I kind of like `where_`. I think this is a lot more intuitive to read and makes it clearer when working with an association query v. the associated records

## Decision

We'll prefix these methods with `where_`

**Comment by paulcsmith** [comment]
Would  love  your thoughts @edwardloveall @jwoertink

**Comment by edwardloveall** [comment]
I forget, can you join inside that association query? like `.where_tasks(&.join_foo)`? If so, `where` might not be the best word because it could get confused with SQL's `WHERE`. I don't feel super strongly on that one though. Is does read really nicely.

**Comment by paulcsmith** [comment]
Yes I believe you can do further joins, but I think if you did a join you'd do another where so might still make sense:

```crystal
```

**Comment by edwardloveall** [comment]
Yeah, I like it.

**Comment by jwoertink** [comment]
Yeah, `where_` reads well, and it's pretty clear.

**Comment by paulcsmith** [comment]
Ok I'll plan to go with `where_` unless someone strongly objects or has an awesome alternative!
