### ISSUE TITLE
Add new tasks for importing and exporting schema

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#168]
Postgres comes with 2 handy tools `pg_dump` and `pg_restore`. These allow you to dump out your entire database to sql, or you can specify just the schema itself. Then you can drop a database, and restore using that dump.

I have a need for this where I don't have migrations because they were all created in rails, but I have the schema dump. I'd like to import that schema, then run specs against it. I imagine we can create 2 new tasks to handle this.
`lucky db.schema.import "/path/to/some.sql"` and `lucky db.schema.export` (generates lucky_export_2019000000.sql)

**Comment by paulcsmith** [comment]
I think this would be awesome! May be good to look at how Ecto does it for some prior art:

* https://hexdocs.pm/ecto_sql/Mix.Tasks.Ecto.Dump.html
* https://hexdocs.pm/ecto_sql/Mix.Tasks.Ecto.Load.html#content
* Lots of good discussion here: https://github.com/elixir-ecto/ecto/pull/901
  * Helpful options here: https://github.com/elixir-ecto/ecto/pull/901/files#diff-c34643168b4a4ab5a0aa4d51635f45c6R187
  * 


I think they do basically what you said. I wonder if we should keep the naming similar to what pg has? `lucky db.schema.restore` and `lucky db.schema.dump`?

**Comment by jwoertink** [comment]
Ooo, that's some good info! Thanks for looking at that. For me personally, I'm 12, and "dump" makes me laugh so I always say "export" 😛 but same naming is fine too 😅

**Comment by paulcsmith** [comment]
I assigned you @jwoertink  because I think you are working on this. But if I'm wrong feel free to remove yourself!

**Comment by jwoertink** [comment]
That's fine. I already have a working concept of this. Just gotta write some specs 😅
