### ISSUE TITLE
Passing custom queries to association join queries

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#171]
It seems to be that this doesn't work:

```crystal
class PostQuery < Post::BaseQuery
  def released
    released_at.not.eq(nil)
  end
end

class UserQuery < User::BaseQuery
  def released_posts
    join_posts.where_posts(&.released)
  end
end

# undefined method 'released' for Post::BaseQuery
# join_posts.where_posts(&.released)
#                          ^~~~~~~~~~~
```

Since the instance passed in [the block](https://github.com/luckyframework/avram/blob/master/src/avram/base_query_template.cr#L89) is the `Post::BaseQuery`, and now `PostQuery`. 

ref: https://gitter.im/luckyframework/Lobby?at=5d3f71fac356af25e0500328

**Comment by paulcsmith** [comment]
This isn't really a bug as much as a confusing API :P

Let's do what we did with preload and require passing in the query rather than yielding a base query. That will make it so you can use methods on your query and it is clearer what is going on.

```crystal
`join_posts.where_posts(PostQuery.new.released)
```

**Comment by jwoertink** [comment]
This will also need to change https://github.com/luckyframework/avram/blob/master/src/avram/base_query_template.cr#L71-L73

I was thinking the signature looks like

```crystal
def where_{{ assoc[:table_name] }}(query : {{ assoc[:type] }}::BaseQuery)
  # some implementation
  self
end
```

The one thing I'm not too sure about is how we take just parts of `query` here. Like in the simple example, I'd expect the sql to look like:
`INNER JOIN posts ON users.id = posts.user_id WHERE posts.released_at IS NOT NULL`. But let's look at a more complex example.

```crystal
# find all users that have joined recently with spam comments on their posts.
UserQuery.new
    .join_posts
    .where_posts(
      PostQuery.new
        .join_comments
        .where_comments(
          CommentQuery.new
            .marked_as_spam
        )
     )
     .recently_joined
```

In the simple example we're basically extracting the `WHERE` part of the `query`, and appending to the main WHERE part of the parent query. In the more complex example, it's almost like a sub select, or maybe we're also extracting the join info?

**Comment by paulcsmith** [comment]
Yeah  I worked on this and there were some issues I ran into. I think what we should do is add something similar to https://api.rubyonrails.org/classes/ActiveRecord/SpawnMethods.html

So when you pass in the query it grabs just the joins, wheres, and maybe a few other things. So it basically works a lot like `merge` and uses `only` under the hood

**Comment by paulcsmith** [comment]
I'm also gonna make it so `where_{{ assoc }}` runs an inner join by default. It is annoying to have to do it yourself every time when 99% of the time that's what you want. I'll also add a `join: false` option that will skip the join for those cases when you want to do something different with the join.  This may require calling unique on the join clauses in case someone does multiple `where_{{ assoc }}` but that should not be too hard

**Comment by jwoertink** [comment]
ah, sweet. Yeah, that makes sense.
