### ISSUE TITLE
When generating SQL makes sure joins, wheres, and raw_wheres are unique

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#175]
Part of making sure #173 is reliable. Duplicate wheres and joins should be flattened before generating SQL. 

We probably want a `wheres/raw_wheres/joins` in the query_builder that call unique. May need to add custom def_equals to wheres and joins to ensure comparison works correctly

**Comment by jwoertink** [comment]
I think this is done already. https://github.com/luckyframework/avram/blob/master/src/avram/query_builder.cr#L307

**Comment by paulcsmith** [comment]
Nice catch!
