### ISSUE TITLE
Query for things that are not nil looks weird.

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#184]
If you want to query with `IS NOT NULL` your first instinct might be to do `thing.not.eq(nil)`, but that throws a compile-time error saying you should use `nilable_eq` instead. So now your query looks like `thing.not.nilable_eq(nil)`. I think we can do better about how that looks. 

Maybe  `is_nil` and `is_not_nil` methods so we get `thing.is_nil` or `thing.is_not.nil` for a type-safe `IS NULL` or `IS NOT NULL`. Another option could be to make `eq` allow a `nil` literal value, but still throw the error for things that may be nilable.

**Comment by paulcsmith** [comment]
We should also only add these methods if the column is nilable
