### ISSUE TITLE
Weird Float64 error

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#200]
I get this error:

> PG::ResultSet#read returned a Float64. A PG::Numeric was expected. (Exception)

This comes from a column `column price : Float64` which is defined in SQL as `price double precision DEFAULT 0.0 NOT NULL`. 

We currently do some weird [conversion](https://github.com/luckyframework/avram/blob/1e0b7e05f2a4a77c89a16ae0fca3606c92cb7206/src/avram/model.cr#L145-L147) stuff most likely due to an old crystal pg bug or something. Chances are that it's not needed anymore.

**Comment by jwoertink** [comment]
The fix for this is pretty easy. After some discussion, we're going to roll with some docs on how to handle this since it's literally just using an alias, and setting your column to that.

```crystal
alias Double : Float64

column price : Double
```

**Comment by jwoertink** [comment]
This will be closed out by https://github.com/luckyframework/website/pull/93 once the next release is live.

**Comment by jwoertink** [comment]
We now have docs that cover this edge case https://www.luckyframework.org/guides/database/models#additional-postgres-types.

**Comment by brunto** [comment]
This seems to not working anymore with lucky 0.26

```
alias Double = Float64
class Agency < BaseModel
    column latitude : Double?
    column longitude : Double?
end
```

The error:
```
PG::ResultSet#read returned a Float64. A (PG::Numeric | Nil) was expected.
```
