### ISSUE TITLE
Helper method in migrations to change the collumn type

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/avram#206]
This came up because we're switching `Int32` ids to `Int64`, `int4` and `int8` in postgres nomenclature respectively. We could have folks set the type of their old primary keys to `Int32`, but then all tables going forward by default would have a different primary key type `Int64`. In addition, new tables that have foreign keys that point to these old tables would have a mixed `Int32` foreign keys and an `Int64` primary key. No good.

The proposed solution is to have people run a migration that changes all keys to `Int64`. Currently, that would have to look something like:

```crystal
class ConvertInt32KeysToInt64::V20190810171432 < Avram::Migrator::Migration::V1
  def migrate
    execute "ALTER TABLE users ALTER COLUMN id SET DATA TYPE bigint"
    execute "ALTER TABLE posts ALTER COLUMN id SET DATA TYPE bigint"
    execute "ALTER TABLE posts ALTER COLUMN user_id SET DATA TYPE bigint"
  end

  def rollback
    execute "ALTER TABLE users ALTER COLUMN id SET DATA TYPE int"
    execute "ALTER TABLE posts ALTER COLUMN id SET DATA TYPE int"
    execute "ALTER TABLE posts ALTER COLUMN user_id SET DATA TYPE int"
  end
end
```

But we think we could make something better. Maybe something like:

```crystal
class ConvertInt32KeysToInt64::V20190810171432 < Avram::Migrator::Migration::V1
  def migrate
    change_column_type :posts, :id, Int64
    change_column_type :posts, :user_id, Int64
    change_column_type :users, :id, Int64
  end

  def rollback
    change_column_type :posts, :id, Int32
    change_column_type :posts, :user_id, Int32
    change_column_type :users, :id, Int32
  end
end
```

**Comment by edwardloveall** [comment]
I tested the first one with some test data, both primary keys and foreign keys, and it seemed to work great. But it was an extremely small dataset, basically one row in each table. Unknown what kind of edge cases are out there.

**Comment by jwoertink** [comment]
I'd like to note on this that postgres supports `bigint`, and `bigserial`. Not tested, but I believe that if you set your id to `bigint`, then it won't auto increment without add a secondary `SEQUENCE` to that table.

```crystal
def migrate
    execute "ALTER TABLE users ALTER COLUMN id SET DATA TYPE bigint"
    execute <<-SQL
      CREATE SEQUENCE public.users_id_seq
        START WITH (SELECT COUNT(*) + 1 users)
        INCREMENT BY 1
        NO MINVALUE
        NO MAXVALUE
        CACHE 1
   SQL
end
```

This is vs doing

```crystal
def migrate
    execute "ALTER TABLE users ALTER COLUMN id SET DATA TYPE bigserial"
end
```

Now, I don't know if this is 100% true or not, but definitely something to keep in mind.

**Comment by edwardloveall** [comment]
Yeah looks like I have some kind of sequence in there because it does auto increment with bitint.

```
$ \d groups
 id         | bigint                   |           | not null | nextval('groups_id_seq'::regclass)
 created_at | timestamp with time zone |           | not null | 
 updated_at | timestamp with time zone |           | not null | 
 title      | text                     |           | not null | 
```

Although Avram must have added this because I sure didn't 😄

**Comment by jwoertink** [comment]
Ah interesting. Ok, well if that's the case, we should just be sure to include a spec that ensures the auto-increment still works after altering the primary key. Also, I guess this could really work for any column, so like if you have a column stored as an int, but want it to be a string.
