### ISSUE TITLE
Feature request: Add support for prefixed KSUID primary_key_type

### ISSUE THREAD

**Issue by m-o-e** [luckyframework/avram#21]
It would be great if lucky_record could support prefixed [KSUID](https://github.com/Sija/ksuid.cr) as a _primary_key_type_. 

Currently the only supported types are bare _int_ and _UUID_.

A modern ID is short, optionally k-sortable and optionally prefixed with an abbreviated model id. Example (from Stripe): `inv_SojvcbC89I7uo5`

It would be great if lucky models could be configured to
generate IDs like the above by adding a line such
as this to the model file:

`primary_key_type KSUID, prefix: 'inv'`

**Comment by jwoertink** [comment]
The PR https://github.com/luckyframework/avram/pull/927 for this was closed out (I assume because the author no longer wants to work on it), but the code wasn't too far off from being done. If anyone would like to take the work started there and finish it up in a new PR, we can get this added in.
