### ISSUE TITLE
Issues with has_one association

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#223]
If you query a `has_one` association from the `belongs_to` side, things work ok.

```crystal
PriceQuery.new.where_line_items(LineItemQuery.new)
```

However, if you query from the `has_one` side, you'll get an error from the wrong foreign key

```crystal
LineItemQuery.new.where_price(PriceQuery.new)
# Error: undefined local variable or method 'line_item_id' for LineItem::BaseQuery
```

This is using the latest Avram, and using the models in the avram spec. 

One other potential issue I didn't look in to is on [this line](https://github.com/luckyframework/avram/blob/master/src/avram/associations/has_one.cr#L14), it doesn't taken in to account for name spaces like the [has_many](https://github.com/luckyframework/avram/blob/master/src/avram/associations/has_many.cr#L9) does.

**Comment by wontruefree** [comment]
I think I am having this exact problem and didn't diagnosis it correctly.

**Comment by jwoertink** [comment]
I'm gonna work on that PR here in a min. Hopefully that will fix the issue.
