### ISSUE TITLE
Need a way to reset limit / offset

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#248]
We already have a [reset_order](https://github.com/luckyframework/avram/blob/master/src/avram/queryable.cr#L60) method. It would be nice to have `reset_limit` and `reset_offset` methods which would let us reset our pagination query stuff. This would be helpful if you have something like:

```crystal
query = PostQuery.new.released.paginate(page: 1, per_page: 12)
# Where the `reset_pagination` method is something you wrote to call `reset_limit` and `reset_offset`
total_posts = query.reset_pagination.select_count
```

WIthout doing this, Avram will throw an exception when using `select_count` https://github.com/luckyframework/avram/blob/master/src/avram/query_builder.cr#L209

**Comment by paulcsmith** [comment]
Good call! We should add those, but we should also make it so the query is cloned after every where/offset/limit so that you don't get these weird mutation bugs.
