### ISSUE TITLE
set_uuid does not run with other before_save calls defined

### ISSUE THREAD

**Issue by russ** [luckyframework/avram#258]
I was trying to create a SaveOperation for a model that has a UUID as a primary key. When running that operation, I was getting errors about the primary key being nil. After digging around, I found that previous_def does not include parent classes.

You can see here, that callbacks calls `previous_def` but that doesn't ever run the before_save defined in the SaveOperationTemplate.

https://github.com/luckyframework/avram/blob/master/src/avram/callbacks.cr#L18
https://github.com/luckyframework/avram/blob/master/src/avram/save_operation_template.cr#L10

I'm using this as a temporary fix. Including that in my operations works. But this is really only good for an app using UUID's exclusively.

```
module UUIDOperations
  macro included
    before_save set_uuid
  end

  def set_uuid
    id.value ||= UUID.random
  end
end
```

**Comment by jwoertink** [comment]
Yeah, it seems in crystal that `previous_def` doesn't know to look up in to ancestors: https://play.crystal-lang.org/#/r/7s7r

I guess that's when you'd call `super`
