### ISSUE TITLE
Forms create methods are generated incorrectly when using virtual attributes together with fillable attributes.

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/avram#26]
Hello, i just found this issues on the create form

1. `VIRTUAL_FIELDS` are not properly passed to the form inside the method.
They are defined here as arguments:
https://github.com/luckyframework/lucky_record/blob/6dfa3e2f801bf810cd4998ec36c9a53f51ab30c2/src/lucky_record/needy_initializer_and_save_methods.cr#L66-L79

But they are not assigned to the form.

2. FIELDS constant used on create method is different on BaseForm and ModelForm:
`Model::BaseForm`: FIELDS have all fields from model.
`ModelForm < Model::BaseForm.`: FIELDS is not defined.

I found this by testing with macros.

3. FIELDS constant is used to generate create methods for the form, so it generates wrong code:
`Model::BaseForm`: generate a create method with all fields.
`ModelForm < Model::BaseForm.`: generate a create method with none field because its not defined.

My solution 
* Assign properly the `VIRTUAL_FIELDS` to the form.
* Set the `FIELDS` constant on inherited forms.
* Create a new constant called `FILLABLE_FIELDS` for generating create methods. Add each field to the constant on the `fillable` macro.
* Validate NEEDS fields not overlap with FILLABLE_FIELDS.

**Comment by paulcsmith** [comment]
Another data point https://gist.github.com/jonnypetraglia/ccab464b7204a0d07be286e854f73e62
