### ISSUE TITLE
Built-in support for mapping a column to an enum

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#270]
It would be nice to have a built-in way to map a column to an enum. My first thought was something like this:

```crystal
table :users do
  column permissions : Int16, enum: User::Permissions
end

user.permissions # => 0
user.permissions_name #=> "Admin"
```

The tricky part here would be when saving in a save operation, would we have a way to map something like `:admin` or `"admin"` to 0, or do we just say you still have to assign the Int16 value? Not totally sure on that front.

ref: https://gitter.im/luckyframework/Lobby?at=5dbc2be69c39821509c32d18

**Comment by wout** [comment]
This something I would like very much. I already have two cases for this feature.

**Comment by jwoertink** [comment]
Yeah, I think this one might be a little trickier since the SaveOperation needs to know if the column is an enum. Then I think we'd need some virtual attribute for the enum so you can pass a number, or pass in a string which would get the value from the enum, and do some validation on that. I haven't had a chance to think through the interface on it.

**Comment by paulcsmith** [comment]
Ok I've been thinking about this a lot and I think this could actually be done with Extremely minimal changes to Avram. To see if it works though could one of you test this out? If it does we can extract a module to make it super easy for anyone to use. 

Here's roughly what I think it would look like

```crystal
class User < BaseModel
  enum Role
    ReadOnly
    Member
    Admin
  end

  class RoleType
    module Lucky
      alias ColumnType = Int32
      include Avram::Type

      def parse(value : String)
         if value.to_i?
           parse(value.to_i)
        else
          FailedCast.new
        end
      end

    def parse(value : Int)
      enum_from_int = User::Role.new(value.to_i)
         if enum_from_int.to_s.to_i? # This is due to Crystal not blowing up if given an int that doesn't match
           FailedCast.new
         else
           SuccessfulCast(User::Role).new(enum_from_int)
         end
    end

    def parse(value : User::Role)
      SuccessfulCast(User::Role).new(value)
    end

    def to_db(role : User::Role) : Int
      role.value
    end

    class Criteria(T, V) < Avram::Criteria(T, V)
    end
    end
  end

  table do
    column role : RoleType
  end
end

SaveUser.create!(role: User::Role::Admin)
UserQuery.first.role # => User::Role::Admin
```

This probably needs some work, but I think this is a decent start. If this works we could extract a macro to create the Avram type automatically without manually writing out all that parsing logic. Does this make sense?

**Comment by wontruefree** [comment]
With this design would the db schema checker ever work?

**Comment by paulcsmith** [comment]
@wontruefree It should still work (I think). Since the `ColumnType` is an `Int32` the db schema checker will check that the `role` column exists and is an Int32

**Comment by confact** [comment]
I got some issues while trying to make this work. Some of the issues are:
* blank? is not defined. Try to make it be an attribute class to add value and blank? methods
* adapter doesn't exist. Add self.adapter with Lucky - maybe should have used Lucky(T)?
* to_db with type StatusType doesn't exist. Try to add a to_db method with StatusType that returns type's value as an enum to return value as an int.
* then I got that they want String and not int to the DB. So I tried to set to_s and that seemed to work, int as string
* I then get the error it couldn't cast Issue::Status to StatusType (the enum)

This is my class for the enum after some changes to make it work which it doesn't - now i got the cast issue:
```crystal
class StatusType < Avram::Attribute(MergeRequest::Status)
  def self.adapter
    Lucky
  end
  module Lucky
    alias ColumnType = Int32
    include Avram::Type

    def parse(value : String)
       if value.to_i?
         parse(value.to_i)
      else
        FailedCast.new
      end
    end

    def parse(value : Int)
      enum_from_int = MergeRequest::Status.new(value.to_i)
       if enum_from_int.to_s.to_i? # This is due to Crystal not blowing up if given an int that doesn't match. Instead it just returns the int you give it. I don't know why this is the case but it is.
         FailedCast.new
       else
         SuccessfulCast(MergeRequest::Status).new(enum_from_int)
       end
    end

    def parse(value : MergeRequest::Status)
      SuccessfulCast(MergeRequest::Status).new(value)
    end

    def from_db(status : Int32) : MergeRequest::Status
      MergeRequest::Status.new(status)
    end

    def to_db(status : StatusType) : String
      status.value.not_nil!.to_s || "0"
    end

    class Criteria(T, V) < Avram::Criteria(T, V)
    end
  end

  def blank?
    value.nil?
  end
end
```

**Comment by lesderid** [comment]
Couldn't we just support the Postgres [`ENUM` type](https://www.postgresql.org/docs/9.1/datatype-enum.html)? (I personally already have existing schemas using them.)

**Comment by paulcsmith** [comment]
@lesderid We could do that, but I think the first pass we'll do it with int. The enum type in postgres is good, but can be a bit of a pain to update and work with so we will require a bit more work to add some nice migration helpers to get it all working as expected
