### ISSUE TITLE
Dockerfile issues

### ISSUE THREAD

**Issue by robbyoconnor** [luckyframework/avram#272]
I fixed these in #271 -- but am posting here: 

1. Docker commands create "layers" -- these layers are immutable. Cleanup must happen in the same layer. Fixed that. 
2. `ADD` is for archive files, -- semantically it behaves like `COPY` but it's bad practice to use it in that manner. Fixed that. 
3. Optimized other stuff as I saw it.

**Comment by jwoertink** [comment]
Thank you!
