### ISSUE TITLE
fill_existing_with generates invalid SQL

### ISSUE THREAD

**Issue by manveru** [luckyframework/avram#278]
The generated query sets `NOT NULL` on the column in the first `ALTER TABLE`, so it fails and can't fill in the existing rows.
Also there seems to be a semicolon missing.

```sql
  ALTER TABLE users
  ADD name text NOT NULL
UPDATE users SET name = 'anonymous';
ALTER TABLE users ALTER COLUMN name SET NOT NULL;
```

**Comment by paulcsmith** [comment]
Thank you for reporting! Is this in an alter or a create block? Just wondering if this happens only for new tables or existing tables
