### ISSUE TITLE
Support for encrypted columns?

### ISSUE THREAD

**Issue by ndbroadbent** [luckyframework/avram#279]
I was wondering if there is anything like the https://github.com/attr-encrypted/attr_encrypted gem for Crystal/Lucky?

If not, it would be really awesome if this could be a project under the luckyframework GitHub organization!

(I'm going through the Gemfile for my Rails app and figuring out what I will need to port. I'm super impressed with Lucky and all the Crystal shards I can find!)

**Comment by confact** [comment]
@ndbroadbent I need this myself and asked @paulcsmith for help to build something. I have now something that at least encrypts and decrypt a string. Haven't yet tested it in models but I will do it as soon as possible and fix any issue with that.

Hopefully, it will solve your issue by using it.

the lib/class is: https://github.com/microgit-com/lucky_encrypted
