### ISSUE TITLE
enhancements: basic guide to raw Avram usage without lucky or lucky cli 

### ISSUE THREAD

**Issue by vectorselector** [luckyframework/avram#290]
If one wants to use Avram, it seems like there should be a basic guide.
Apart from the Lucky Framework documentation (which is comprehensive and great by the way!) only the API documentation for Avram appears to exist. (the readme.md here only shows how to add the shard.) and the Lucky docs refer to the lucky cli scaffolding etc.
By the way, the source from Avram looks to be the simplest cleanest ORM I've seen yet for Crystal.
I'll definitely give Lucky a go on my next greenfield project

**Comment by vectorselector** [comment]
not trying to make more busywork here... as soon as I figure out how to use raw Avram i'll make a modified readme.md and submit it...just providing the rationale, or in case there are other resources I missed someone will point them out...

**Comment by vectorselector** [comment]
oh my, there's some coupling here, ok. I'll check back later.

**Comment by jwoertink** [comment]
Before it was renamed to Avram, I had an example of using LuckyRecord in standalone [here](https://github.com/jwoertink/crystal_orm_test/blob/master/src/orm_test/lucky_record/setup.cr). I know there's a bit of coupling that assumes you're using Lucky (which hopefully we can take out one day), but there might be a way to use Avram outside of Lucky with a few deps.

**Comment by yb66** [comment]
I came here looking for the same thing. What I would say is that without standalone examples then close to zero people will use it that way and there'll never be any necessity to decouple from Lucky, there'll always be something more important to do.  I think this should be reopened as a feature request.

The link jwoertink kindly provided has died, I think [this](https://github.com/jwoertink/crystal_orm_test/blob/c9479c95c9d3223af9c3c81fb4e4eda3f4b7d29d/src/orm_test/lucky_record/setup.cr) should work.

Regards,
iain

**Comment by jwoertink** [comment]
Oops, yeah, the link is dead, but so is LuckyRecord 😂  Here's a setup using Avram outside of Lucky https://github.com/jwoertink/crystal_orm_test/blob/master/src/orm_test/avram/setup.cr 

I guess we could update the README with some setup docs. If anyone is open to submitting a PR, that would be nice.
