### ISSUE TITLE
Investigate pg_dump vs pg_dumpall

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#291]
Right now when we use the `luck db.schema_dump` task, it runs `pg_dump -s` to only dump the schema. I just came across `pg_dumpall --schema-only` which might do the same? 

I don't know the difference, but this will need to be investigated to see if the current method of doing a schema dump is the proper way, or if `pg_dumpall` is a better way.

**Comment by jwoertink** [comment]
Alright, here's the difference:

* `pg_dumpall` - this utility will allow you to also include user roles and globals. However, this utility doesn't seem to include alternate formats which are used with `pg_restore`. It also uses a few slightly different CLI args than other utilities `pg_dump -s my_db` VS `pg_dumpall -s -l my_db`. Lastly, you can backup more than just your DB with this, you can do your whole PG cluster.
* `pg_dump` - this utility allows you to specify an alternate format other than raw SQL like tar. This takes the same args as psql, and pg_restore, and some others. 

I think we can keep the `pg_dump` as is for now. `pg_dumpall` can be used manually for edge case stuff.

**Comment by paulcsmith** [comment]
Sounds good! Nice write up and investigation
