### ISSUE TITLE
select_sum fails on Int64 columns

### ISSUE THREAD

**Issue by bdtomlin** [luckyframework/avram#292]
It appears that sum doesn't work with Int64 columns. It does work with Int32 which is the type used in Avram's tests here:

https://github.com/luckyframework/avram/blob/d1d6b63cf67e779a1d902d9d13aa446253c3f3d7/spec/query_spec.cr#L378-L394

This failure can be seen with this test:
```crystal
    it "returns the sum with Int64" do
      UserBox.create &.age(2)
      UserBox.create &.age(1)
      UserBox.create &.age(3)
      sum = UserQuery.new.id.select_sum
      sum.should eq 6
    end
```

and here is the error message:

```
Failures:

  1) Avram::Query #select_sum returns the sum with Int64

       cast from PG::Numeric to Int64 failed, at /Users/bryantomlin/dev/_src/avram/src/avram/criteria.cr:120:5:120 (TypeCastError)
         from src/avram/criteria.cr:120:5 in 'select_sum'
         from spec/query_spec.cr:391:7 in '->'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/example.cr:255:3 in 'internal_run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/example.cr:35:16 in 'run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/context.cr:296:23 in 'internal_run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/context.cr:291:7 in 'run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/context.cr:296:23 in 'internal_run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/context.cr:291:7 in 'run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/context.cr:48:23 in 'run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/spec/dsl.cr:270:7 in '->'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/kernel.cr:255:3 in 'run'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/crystal/main.cr:47:5 in 'main'
         from /Users/bryantomlin/.asdf/installs/crystal/0.32.1/src/crystal/main.cr:106:3 in 'main'
```

**Comment by jwoertink** [comment]
That's interesting considering that the method returns `Int64`. https://github.com/luckyframework/avram/blob/master/src/avram/criteria.cr#L118 I wonder if that error happens at a lower level like in the PG shard itself 🤔

**Comment by bdtomlin** [comment]
Yeah, it's definitely strange. I haven't had time to really dig in and figure out how this all works, but I can force it to work by changing
https://github.com/luckyframework/avram/blob/d1d6b63cf67e779a1d902d9d13aa446253c3f3d7/src/avram/criteria.cr#L118-L121
to
```crystal
  def select_sum : Int64
    rows.query.select_sum(column)
    rows.exec_scalar.as(PG::Numeric | Int64).to_f.to_i64
  end
```

**Comment by bdtomlin** [comment]
So it looks like there are a few issues with `select_sum`.

1. `select_sum` should not return an Int64. That would not be able to work as expected on a column with floats/decimals.
2. `select_sum` fails when there are no records. This should instead return 0 in my opinion.
3. The pg driver returns Nil, PG::Number, or Int64 depending the query result, which causes using `rows.exec_scalar.as(Int64)` to fail in two of those three scenarios.

I propose that we always return a Float64 when using `select_sum`. If there are no records in the query, then we return 0_f64.

The following is how I am currently handling it in my app. I also have tests for this. If everyone is happy with this approach I will create a PR. If there are other/better ideas let me know.

```crystal
  def select_sum : Float64
    rows.query.select_sum(column)
    if sum = rows.exec_scalar
      sum.as(Int64 | PG::Numeric).to_f64
    else
      0_f64
    end
  end
```

**Comment by jwoertink** [comment]
Also related to the failing with no records: https://github.com/luckyframework/avram/issues/297

**Comment by paulcsmith** [comment]
@bdtomlin very nice investigation and write up! Thanks for doing that. 

I think select_sum in the QueryBuilder should match the pg adapter pretty closely with a numeric and float and nil. Just so if someone needs to they can get whatever they want

But select_sum in criteria could use V. This would be insanely cool I think because it’ll get the type of the column and try to cast to those. So if you have an Int64 it’ll do that. If you have a Float it’ll use that. 

Does that make sense, and does that seem good?

As for how to handle null...I’m not sure. I can see it being 0 or being nil. I’m leaning toward nil because it is easier to handle and a bit more flexible. Meaning if you want to use 0 to you can do `select_sum || 0` but going the other way is harder. The other thought is that if there is no sum because there are no records I would often want to do something different.

The downside is if you want to treat it as 0 every time, then you’ve got to do that yourself. I think this may be ok. We could also consider adding a select_sum! And that could do 0?

Thoughts?

**Comment by bdtomlin** [comment]
@paulcsmith I understand returning nil, that makes sense. I definitely like the idea of `select_sum!` since that makes it a lot easier to do things without a bunch of nil checks. I use select_sum a lot for analytics. My end user just want's to know how many visits, form fills, etc. It seems like a common enough use case to support it.

---

There are some other subtleties with the types and I don't think using `V` will work in this case. If you sum an `Int32` column, you get an `Int64` from the pg driver. Any other column including Int64 gives you a `PG::Numeric`. That is why Avram's tests were passing but sum on Int64 columns failed.

Maybe the return type from `select_sum` should be `Int64 | Float64 | Nil` and the method does the following:

* If the pg driver gives us an `Int64`, we send it on.
* If the pg driver gives us a `PG::Numeric` with no decimals we convert it to `Int64`
* Convert other `PG::Numeric`s to `Float64`
* Send `nil` for no results

The other option is to send a `Float64` for all `PG::Numeric`s

**Comment by bdtomlin** [comment]
@paulcsmith, I think I misunderstood what you were saying with `V`. So if `V` is any type of Int convert the return value to an Int64, if `V` is any type of Float convert to a Float64.

So the return type of the method would be `Int64 | Float64 | Nil`.

Then there would also be a method select_sum! that does the same but with the return type `Int64 | Float64`.

I like that really well. Is that what you were saying? If so I would be glad to take a crack at it and create a PR.

**Comment by paulcsmith** [comment]
@bdtomlin I didn’t realize the problems you outlined at first so I think you understood me and my method just wouldn’t work haha. But I like what you are proposing, but with one modification. In the base criteria class you could do what you’re proposing, but you could override the method in the Int32, Int64 and float extension classes so that it always does the right cast. That way the return type is always correct and you don’t have to work with the union!

It’d look like:

```crystal
# in the int extensions 
def select_sum : Int64?
  super.as(Int64?)
end
```

**Comment by bdtomlin** [comment]
@paulcsmith Nice. I'll put this together this afternoon.

**Comment by jwoertink** [comment]
Also note that in a future release (not the next one) we will be able to do a rescue on `DB::NoResultsError` to catch things like `select_sum` not returning results

**Comment by bdtomlin** [comment]
@jwoertink I'll try to find that issue and see what the plan is.

@paulcsmith I added a pull request that will hopefully be a good way for us to have a more clear conversation on this. I think the implementation is what you intended, but definitely let me know your thoughts.

**Comment by jwoertink** [comment]
@bdtomlin it was just merged in to crystal-db, so until they release a new version, and we update support for that, we won't be able to use it. More of just a note for future updates.
