### ISSUE TITLE
Can not save empty array

### ISSUE THREAD

**Issue by Anonyfox** [luckyframework/avram#294]
In my model: 

```crystal
table do
    ...
    column links : Array(String)
    ...
  end
```

In my migration:

```crystal
add links : Array(String), default: [] of String
```

when saving: 

```crystal
SaveMyModel.create!(links: [], ...)
```

fails with 

```bash
Exception Could not save SaveMyModel.
22:19:39 web.1   |    ▸ links: is required
22:19:39 web.1   |   (Avram::InvalidOperationError)
22:19:39 web.1   |    from lib/avram/src/avram/save_operation.cr:304:7 in 'save!'
```

**Comment by jwoertink** [comment]
Do you have a validation on that model for that field?  I know the validate_required checks `.blank?` which would be true on an empty array. We may need to add an option or something for that.

**Comment by Anonyfox** [comment]
I didn't specify any validations manually. Can I turn off these validations somehow? Something like `links : Array(String)?` doesn't work unfortunately

**Comment by jwoertink** [comment]
Since the default is set in the column, are you able to save it without passing `links`? Just pass all of the other ones with values, and see if that works. If not, then it's probably an issue we will need to figure out and fix 😕

**Comment by Anonyfox** [comment]
Nope, just tried that, too.

**Comment by paulcsmith** [comment]
You can try doing this in your save operation to reset errors:

```
before do
  links.reset_errors # This will remove errors that were done by Avram
end
```

I think the real fix might be to change `Array#blank?` to return true all the time. In my mind if the array is empty it is not blank. It is still there. I've been bitten by this in Rails and have seen others bitten by it too.

Thoughts?

**Comment by Anonyfox** [comment]
thanks for the fix!

on the general issue: I do use Elixir/Phoenix/Ecto every day at work, and at least in my opinion the `[]` is a non-null value (with size zero, but still). Same as `{}` is a valid JSON and not null, right?

**Comment by paulcsmith** [comment]
@Anonyfox yes I agree! They should not be treated as null. We'll definitely fix this :)
