### ISSUE TITLE
No results on a select_count

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#297]
This may not be Avram, but I need to start somewhere. My latest lucky app keeps getting this error:

```text
Exception no results 
    lib/db/src/db/statement.cr:18:7 in 'scalar:args' <file>
    lib/avram/src/avram/queryable.cr:199:7 in 'select_count' <file>
    /usr/share/crystal/src/float.cr:228:3 in 'perform_action' <file>
    lib/lucky/src/lucky/route_handler.cr:0:7 in 'call' <file>
    /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call' <file>
    /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call' <file>
    /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call' <file>
    /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call' <file>
    /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call' <file>
    lib/lucky/src/lucky/context_extensions.cr:13:5 in 'call' <file>
    /usr/share/crystal/src/http/server/request_processor.cr:48:11 in 'process' <file>
    /usr/share/crystal/src/fiber.cr:255:3 in 'run' <file>
    ??? <file>
```

Notice that the stack trace doesn't actually say where in my code this is being called. The only way I can tell is from looking at bugsnag and seeing the path that was called and the action. So that leads me to the only bit of code on that action calling `select_count` which is:

`results.clone.reset_limit.reset_offset.select_count` results is just a Query object. 

The strange thing that makes me think this may not be Avram is just that, it's obviously running a SQL query, but instead of getting back Int64, it's raising a no results exception. This should always be a number....  hmm... Maybe we can catch this error and just return 0?

**Comment by paulcsmith** [comment]
Maybe it’s a bug in the Postgres or crystal db shard? Can we reproduce this with a spec?

**Comment by jwoertink** [comment]
It's intermittent. My guess is maybe something with a db connection dying in the pool, but I have no idea how to recreate it. I posted on the DB shard as well. Maybe someone will have an idea on how we can test this.

**Comment by jwoertink** [comment]
Ok, found the issue. We were able to replicate it, and it also turns out it was only intermittent because the page it was landing on was only being hit by some people. Here's a query to reproduce this.

```crystal
og_query = UserQuery.new.distinct_on(&.age).group(&.age).offset(0).limit(10).name.asc_order
total_count = og_query.clone.select_count
```

This will run `SELECT DISTINCT ON (users.age), COUNT(*) .... FROM users ....` because it doesn't reset the distinct. When the query runs, it literally returns no results, and that throws an exception. I'll try and do a PR in a bit for this

**Comment by paulcsmith** [comment]
Awesome find. I think we should also consider catching db errors like that, logging the query that caused it, and then re raising it. That way this stuff is easier to find

**Comment by jwoertink** [comment]
> logging the query that caused it, and then re raising it.

oh god yes... because that was a little ridiculous 😂 It was some good super sleuthing by @russ

**Comment by jwoertink** [comment]
Alright, so even more digging in. It looks like postgres does actually allow both a count and distinct.

```
db=# select distinct on(name) count(*) from actors group by name;
 count
-------
     2
(1 row)
```

Where this gets a little funky is when you add a where clause, and it doesn't match

```
db=# select distinct on(name) count(*) from actors where name_starts_with = 'A' group by name;
 count
-------
     2
(1 row)

db=# select distinct on(name) count(*) from actors where name_starts_with = '@' group by name;
 count
-------
(0 rows)

db=# select count(*) from actors where name_starts_with = '@';
 count
-------
     0
(1 row)
```

So simply just removing the distinct isn't a good solution because we don't know what the intention was. I think the best place to start here is first get crystal-db to raise an actual class instead of a raw string. Then hopefully that gets merged in, and we can then catch that error, and do all the other stuff.

**Comment by jwoertink** [comment]
Just merged in now allows us to rescue `DB::NoResultsError`

**Comment by paulcsmith** [comment]
I believe that this was covered by #292. If you test it and it works now could you close this?

**Comment by jwoertink** [comment]
That PR fixed all the aggregates except `select_count` 😂 so looks like this is still valid.
