### ISSUE TITLE
Better name for Forms

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#30]
Brought to my attention here: https://gitter.im/luckyframework/Lobby?at=5a5925eb97cedeb0482dec9e

"Form" may note be the best name because you can use "Forms" for things that are not ever saved with a traditional form. For example, you might use a LuckyRecord "Form" for saving something from a CSV. It's also confusing to talk about because it's unclear if you're talking about a LuckyRecord "Form" or an HTML form. JSON APIs also doesn't use "forms." 

I'd love to come up with a better name. "Saver" or "Commiter" makes sense, but sounds super weird: `UserSaver`, etc.

Some other ideas are to come up with some other term that can take on its own meaning, similar to how Trailblazer has "Cells". It doesn't really mean anything in software so it can take on its own meaning. Feel free to post ideas here :)

Brainstorming:

* `UserSaver`
* `UserCommiter`
* `UserForge`
* `UserMutation`
* `UserChangeset`
* `UserRecord`
* `UserTransaction`
* `UserOperation`
* `UserReactor`
* `SaveUser`

**Comment by jonnypetraglia** [comment]
I'll add my two cents as someone who is familiar with Lucky, but still remembers what it was like to go through the guide in the beginning.

When I first saw `UserQuery`, I new exactly what it was intended to do. `UserForm` was very confusing because I thought it referred to HTML (so note: glad this ticket exists).

As to what's been proposed, my vote would be for `UserTransaction`, `UserChangeset` (does `SignInChangeset` work though?), or `UserBuilder`. I find both `UserOperation` & `UserData` to be too vague, as well as the fact that `Data` sounds more property-based than method-based, and I find having `User` in it already tells me what data it is going to pertain to.


I'm going to propose a slight twist on `Transaction`: `Action`. It is slightly less specific but also less of a mouthful.

```crystal
class UserAction < User::BaseAction
  allow name
end

UserAction.create(params) do |t, user|
  if user
    p "success"
  else
    p "failed"
  end
end

UserAction.update(user, params) do |t, user|
  if t.saved?
    p "success"
  else
    p "failed"
  end
end

needs user_action : UserAction

def inner
  form_for Users::Create do
    text_input @user_action.name
  end 
end
```

**Comment by paulcsmith** [comment]
@jonnypetraglia Thanks for starting this up again. It has been on my mind a lot lately. One problem with `UserAction` is that we already have `Actions` that handle the routing and HTTP request/response. We *could* rename that to something like `Endpoint` or even `Controller` but I worry `Controller` is too overloaded and people may have different expectations.

I'd like to propose something else that I have been thinking about but haven't written up until now.

## The background

* `Form` is confusing. I think we all agree on that :P
* Not all `Forms/Whatever` are tied to a database, e.g. `SignInForm/Changeset/Whatever`

## A new way of looking at it

Rather than including the name of the object, we just omit it completely and use verbs

* `SaveUser`
* `SignInUser`
* `CreateAdmin`

You could also have separate operations for Create/Update if they are significantly different

* `CreateUser`
* `UpdateUser`

These would inherit from an `Operation` defined by the model or inherit from a `Lucky::Operation`. We'll focus just on the `Operation` defined in the model

```crystal
class User < BaseModel
  # when using `table` macro it will set up a `SaveOperation` class (instead of the `BaseForm` we use now)
end

class SaveUser < User::SaveOperation
  fillable name, email, etc
end

# In an action
SaveUser.create(params) do |op, user| 
  # op is short for operation. but you can use whatever you want
  # Maybe even `save` so you could do `if save.success?`
  if op.success? && user
     # do success
  else
    # do failure
  end
end

# In a Lucky HTML page
class Users::NewPage < MainLayout
  needs save_user : SaveUser

  def render
     new_user_form(@save_user)
  end

  private def new_user_form(op : SaveUser)
    form_for Users::Create do
       text_input op.name
       email_input op.email
    end
  end
end
```

I think the naming is super clear with this approach. It is also far more flexible because you could have an "operation" in `src/operations` that doesn't interact with the database of form params and it would still make sense conceptually. Like `ChargeStripeUser` or something. 

Thoughts?

**Comment by jwoertink** [comment]
I've been using the forms like mutations. I use [this gem](https://github.com/cypriss/mutations) A LOT in my rails projects for passing in params and handling updates and stuff so I just always assumed Forms was the same thing. 

I do like the `UserTransaction` name, but would that make an assumption that calls are wrapped in a sql transaction? Maybe not? I also like the `Operation` name. 

One thing to keep in mind is that we also have the Virtual stuff to consider. Also what would become of [Fields](https://github.com/luckyframework/avram/blob/master/src/avram/field.cr)? Would those stay the same name, or be renamed as well?

**Comment by jonnypetraglia** [comment]
@paulcsmith Ah, I totally forgot Action was already used. So bad suggestion, but I'm glad it kickstarted the issue.

I actually forgot to say, I do like `SaveUser`. I think your new approach is great, that would be my final vote, really.

**Comment by paulcsmith** [comment]
I've never seen that gem, but yeah this is very similar! And I like that they don't add "Mutation" to the names of the object.

Re: `UserTransaction`, when you save or update a form object right now it does wrap it in a transaction. That way your before/after callbacks are wrapped in the transaction. That should be documented better though :)

One thing I like about `Operation` is that it works well for what we now call `VirtualForm`s as well as the more traditional database backed forms. I'd love to have a `Lucky::Operation` that takes the place of `Avram::VirtualForm` since VirtualForms really have nothing to do with saving data to the database :P I think we can focus on Avram for now and then later do some more abstractions once we understand things better.

I'm not sure about `Field`. I would love a better name for that. I'm open to suggestions on that but I'd also be ok keeping them for now so we don't introduce too much change at once

**Comment by jwoertink** [comment]
Just posting [this gem](https://github.com/AaronLasseigne/active_interaction). Another one I've used.

These could be nice
`UserCreate < Avram::Operation`
`UserCreate < Avram::Interaction`

**Comment by edwardloveall** [comment]
I like `Operation` a lot! It feels like it's the right level of abstraction for both interacting with the database (create a user) and sending data around the app (sign in that user).
