### ISSUE TITLE
Skipping preload when no there's no results

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#305]
I'm not sure if this is even doable, but just in case, I'm gonna leave this here. 

If you do:

```crystal
PostQuery.new.preload_author.released_at.gte(2.hours.ago)
```

This will do a query for authors where the post_id is in whatever the ids returned from the `PostQuery` are.... However, if no posts are returned from that query, then you get this `SELECT * FROM authors WHERE id IN []` . It's an unnecessary query. So if we have a way to skip it when no results are returned, we could see a nice little performance boost (we being my app team, but probably others too 😅 )

**Comment by paulcsmith** [comment]
This seems possible and would be a great idea! 

I think it would be changing the preloads like this:

https://github.com/luckyframework/avram/blob/1a9018d9d37015c775404326ed1f33d9246554fd/src/avram/associations/has_one.cr#L55

To:

```crystal
{{ assoc_name }} = ids.empty? ? [] of {{ model }} : preload_query.dup.{{ foreign_key }}.in(ids).results.group_by(&.{{ foreign_key }})
```

So if ids are empty it just returns an empty array of the association and therefore will not query the db

**Comment by jwoertink** [comment]
oh nice! Maybe I'll give that a shot

**Comment by jwoertink** [comment]
Ok, so quick testing shows that changes the type signature, and all kinds of stuff starts blowing up. I'll need to dig in more to see what's up. 

Any idea on how I could write a spec for this? Right now I just look for the query to show up in the log, but not sure how to test if it makes a connection to the DB or not.
