### ISSUE TITLE
SchemaMismatchError if an ephemeral table conflicts with the existing database (because of SchemaEnforcer)

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/avram#308]
Let's say you're adding usernames to your user model when before you only had an email address. One problem is, you must add values the new `username` column using `fill_existing_with`, which doesn't take a dynamic value.

One solution is to:

* Create a nullable field and `fill_existing_with: :nothing`
* Create a temporary model with an optional `username`
* Use that temp model to generate unique usernames
* Migrate so the `username` field is now required

That's what I did in [my app](https://github.com/edwardloveall/lucky_bits/blob/5004faf83d2918e615231c90c00a24b5435d303d/db/migrations/20190120141952_generate_usernames_for_users.cr#L5).

But now that Avram's `ensure_correct_column_mappings!` is added, it complains that the temporary model (which is still technically a model) has a field (nullable `username`) that doesn't match the database (non-nullable `username`)

@paulcsmith made a suggestion:

>We should have a way to ignore models in the enforcer for stuff like this! Could you open an issue? I’m thinking a simple macro like “skip_column_enforcer” or something

**Comment by jwoertink** [comment]
We should just make `fill_existing_with` take a dynamic value

**Comment by paulcsmith** [comment]
Yeah also that! Yield a block with each record or something. So if you need to you can use information in the existing record. Or just leave it out if you don’t need it

I still think ignoring a model is good though. For cases where there is a temporary table for a script or more advanced migration
