### ISSUE TITLE
Creating a Box for a model with only default columns raises an error.

### ISSUE THREAD

**Issue by wout** [luckyframework/avram#309]
Let's say I have this model:

```crystal
class Account < BaseModel
  table do
  end
end
```
And the following box:

```crystal
class AccountBox < Avram::Box
  def initialize
  end
end
```

Then running this spec:

```crystal
require "../spec_helper"

describe Account do
  it "is createable" do
    account = AccountBox.create
  end
end
```

Will raise the following error:

```crystal
Nil assertion failed (NilAssertionError)
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/nil.cr:106:5 in 'not_nil!'
         from lib/avram/src/avram/save_operation.cr:302:7 in 'save!'
         from src/models/account.cr:2:3 in 'create!'
         from spec/models/account_spec.cr:7:7 in '->'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/example.cr:255:3 in 'internal_run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/example.cr:35:16 in 'run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/context.cr:296:23 in 'internal_run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/context.cr:291:7 in 'run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/context.cr:296:23 in 'internal_run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/context.cr:291:7 in 'run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/context.cr:48:23 in 'run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/spec/dsl.cr:270:7 in '->'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/kernel.cr:255:3 in 'run'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/crystal/main.cr:47:5 in 'main'
         from /home/wout/.crenv/versions/0.32.1/share/crystal/src/crystal/main.cr:106:3 in 'main'
         from __libc_start_main
         from _start
         from ???
```

But the issue extends beyond an empty model. If the model has just one additional, nilable column, and the box does not define a value for that column, the same error is thrown.

**Comment by wout** [comment]
I think I found a fix for the issue. It reminded me of some strange behaviour I noticed while working on the `changed?` implementation. In save_opteration.cr `def save`, changing `if valid? && changes.any?` to `if valid? && (!persisted? || changes.any?)`, makes the error go away.
In the `changed?` implementation that's already the case, so it can be tested easily.

**Comment by jwoertink** [comment]
Ah. I see. Yeah, I guess that makes sense because there's nothing to change when there's no columns. Good find. I wonder if we have edge cases tested for that. Like, would making that change break anything else? I don't think so, but not 100% sure.

**Comment by wout** [comment]
It's already tested and merged by @paulcsmith.

You'll find it here:
https://github.com/luckyframework/avram/blob/master/src/avram/save_operation.cr#L274

But maybe some additional tests should be added for Boxes? Just to cover the case?

**Comment by jwoertink** [comment]
Ah, I see what you're saying. Yeah, it would be nice to have a test case for when there's no columns. Just so we don't break that in the future.

**Comment by paulcsmith** [comment]
Ohhh, we just need to release a new version for Avram :P. Yeah I think an additional test for Box would not hurt!

**Comment by jwoertink** [comment]
This is fixed on master now, and covered by the recent specs.
