### ISSUE TITLE
Operation.new should take keyword args

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/avram#318]
Currently, only `create` and `update` take named args, like so:

`Membership.create(group_id: 1, user_id: 2)`
`Membership.update(membership, group_id: 2)`

If you ever need to test this however, you may want to just instantiate a membership without running it to test validations or other in-operation logic. To do this, you have to actually run the `create` or `update` methods. I think running `new` and passing in the same arguments would be more expected.

However, we can't right now. `new` only takes params which are a pain to create especially if they are nested. Ideally we could do something like:

```crystal
Membership.new(group_id: 1, user_id: 2)
```

**Comment by jwoertink** [comment]
Would this be a good good use for a `.build` method? Or does it make more sense to just define the initializer for this?

**Comment by edwardloveall** [comment]
`build` could work, but I think `new` would be best for the [principle of lease surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). If we can't use `new` or it's really hard then `build` would be a good 2nd choice.

**Comment by jwoertink** [comment]
Oh yeah, for sure. I guess we can do an overload. One that takes params, and another that takes the named args.
