### ISSUE TITLE
Add “reset_where” to queryable

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#319]
So you can remove where clauses. Helpful for removing defaults where’s

```crystal
# let’s say UserQuery.new is overridden and adds deleted_at.is_nil
# you could use reset to remove the where
UserQuery.new.reset_where(&.deleted_at)
``` 

Works similarly to distinct_on where you use a block so it reads better.

**Comment by wout** [comment]
I'll take care of this. Just wondering, since we already have `#reset_order`, `#reset_limit` and `#reset_offset`. Would you use `#reset` or `#reset_where`? The `#reset` method might as well be a method to reset them all.

**Comment by paulcsmith** [comment]
@wout Great thought. I think `reset_where` makes it clear what it is resetting. Thank you for working on this!

I think we can avoid `reset` since I thikn being explicit about what you want to reset is probably a bit safer. If someone has a use case for it with a compelling example then we can reconsider though!

Here are some bits of code that I think will be relevant to this:

* Add method to Queryable https://github.com/luckyframework/avram/blob/b47b09bf3470fef4419fcad06174cea09550f8d3/src/avram/queryable.cr#L75-L79.This is where yu'd add `reset_where`
* Add `__reset_where` method on criteria https://github.com/luckyframework/avram/blob/b47b09bf3470fef4419fcad06174cea09550f8d3/src/avram/criteria.cr#L133-L135
* Add `reset_where` to QueryBuilder: https://github.com/luckyframework/avram/blob/b47b09bf3470fef4419fcad06174cea09550f8d3/src/avram/query_builder.cr#L158. 
* Reset where should remove the wheres for the given column: https://github.com/luckyframework/avram/blob/b47b09bf3470fef4419fcad06174cea09550f8d3/src/avram/query_builder.cr#L7

Feel free to ping me here or in Gitter if you need anything

**Comment by wout** [comment]
Thanks for the roadmap! ☺️
