### ISSUE TITLE
Add Avram::SoftDelete

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#320]
Depends on https://github.com/luckyframework/avram/issues/319

Module to include in models that adds “soft_delete”. Another module to include in queries to add “only_soft_deleted”, “not_soft_deleted” and other scopes. We could also consider going with the “discard” name to match the ruby gem below

This lib would be similar to https://github.com/jhawthorn/discard

**Comment by wontruefree** [comment]
This is such a common use-case I am surprised more frameworks dont have this
