### ISSUE TITLE
DatabaseCleaner.table_names excludes "schema_migrations" but should be "migrations"

### ISSUE THREAD

**Issue by mikeeus** [luckyframework/avram#33]
https://github.com/luckyframework/lucky_record/blob/f3990dd4113234c900c6cc34313283b46ab66190/src/lucky_record/repo.cr#L29-L31

The migration tracking table in LuckyMigrator is just `migrations`, so I think this is a mistake. It probably was changed on `LuckyMigrator` but wasn't reflected here.

**Comment by jwoertink** [comment]
Looks good. Closing this out. Thanks all!
