### ISSUE TITLE
Investigate moving away from DB.mapping

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#364]
Possibly in the next Crystal release, `JSON.mapping` and `YAML.mapping` will be deprecated https://github.com/crystal-lang/crystal/pull/9272 in favor of using Serializable

In the crystal-db shard, `DB.mapping` was made to mimic those APIs. To keep up with that, a `DB::Serializable` was added https://github.com/crystal-lang/crystal-db/blob/master/src/db/serializable.cr

I haven't seen an issue yet, but I'd imagine `DB.mapping` could go the same way. Right now it's used [here](https://github.com/luckyframework/avram/blob/master/src/avram/model.cr#L212). Maybe this could clean up our code?

**Comment by paulcsmith** [comment]
Good idea. I think we should do this and I think it'd make implementation a lot simpler 👍

**Comment by jwoertink** [comment]
whoomp there it is https://github.com/crystal-lang/crystal-db/pull/196 Time to bring https://github.com/luckyframework/avram/pull/468 back.
