### ISSUE TITLE
Rename column in migrations

### ISSUE THREAD

**Issue by wout** [luckyframework/avram#365]
Shouldn't we add a `rename` method to rename columns using migrations?

```crystal
alter table_for(User) do
  rename :old_name, :new_name
end
```

**Comment by jwoertink** [comment]
I was like "we already have it...." Then I went to go look for it, and couldn't find it 😅  I guess we overlooked this. Good catch!

**Comment by jwoertink** [comment]
Looks like this is now a thing! Thanks for tackling that 🎉
