### ISSUE TITLE
create_index name collisions

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#367]
These two statements will result in a collision on the name of the table generated.

create_index :url_paths, [:folder_id, :redirect_id, :forum_id, :page_id, :product_id, :manufacturer_id, :topic_id, :user_id, :post_id]
    create_index :url_paths, [:folder_id, :redirect_id, :forum_id, :page_id, :product_id, :manufacturer_id, :topic_id, :user_id, :post_id, **:path**], unique: true

The index name is truncated and the second index name thus does not include any mention that it's different from the first index in that :path has been added.

Suggested solution: don't use a truncated string of concatenated field names. The index name should be the table name followed by a numerical hash of all of the concatenated field names, perhaps in base 36 so that it is a compact alphanumeric representation.

**Comment by jwoertink** [comment]
Oh, good suggestion! Thanks for reporting

**Comment by jwoertink** [comment]
This is fixed by #386
