### ISSUE TITLE
Change how `validate_uniqueness_of` query works

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#368]
> See https://gitter.im/luckyframework/Lobby?at=5ebdf71bf3ce603074bc908a for some background on the issue

So it uses a query and doesn't end with a criteria. When I originally wrote this I didn't know how else to do it. But I figured out a better way to do it in AvramSlugify.

## Now

```crystal
validate_uniqueness_of name, query: UserQuery.new.project_id(1).name # Need to end with `name` criteria
```

## After

```crystal
validate_uniqueness_of name, query: UserQuery.new.project_id(1) # Just use a query
```

Do this by using the passed in attribute's name and a raw where. Still (mostly) type-safe because the attribute is typed and auto-generated by the model

**Comment by matthewmcgarvey** [comment]
Switching to this style would remove the ability to change how the value is searched by. If you wanted to check for the uniqueness of a string case insensitively you can do `validate_uniqueness_of name, query: UserQuery.new.name.lower` currently. We could add additional parameters for certain column types to compare in different ways though String might be the only one that needs it.

**Comment by paulcsmith** [comment]
That’s a good point. Maybe we allow either one? So you can return a criteria if you want to customize but it is not required. What do you think?

**Comment by matthewmcgarvey** [comment]
This is the link to the avram_slugify that should be referenced https://github.com/luckyframework/avram_slugify/blob/be75b34e358e6dc2f6d9ad8d9ed079754b945ad2/src/avram_slugify.cr#L29
