### ISSUE TITLE
Querying with a join table can produce invalid SQL

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#370]
## Summary

In this instance I'm working with 3 models
- Business
- User
- Contributor

The contributors table is a join table between the other two. I'm writing a query to load a contributor but I want it limited to the current business and make sure that the current user has access to that business to be able to view the contributor.

My avram code looks like:

```crystal
business_query = BusinessQuery.new
  .id(business_id)
  .where_users(UserQuery.new.id(current_user.id))
ContributorQuery.new
  .where_businesses(business_query)
  .find(contributor_id)
```

When I run this code, it fails with the error `table name "contributors" specified more than once`

You will notice that I have a has many through set up on Business to be able to call `where_users` but I've tried it with `where_contributors` and it doesn't change anything.

## Generated SQL

```sql
SELECT contributors.id, contributors.created_at, contributors.updated_at, contributors.user_id, contributors.business_id
FROM contributors
INNER JOIN businesses ON contributors.business_id = businesses.id
INNER JOIN contributors ON businesses.id = contributors.business_id
INNER JOIN users ON contributors.user_id = users.id
WHERE businesses.id = $1
  AND users.id = $2
  AND contributors.id = $3
ORDER BY contributors.id ASC
LIMIT 1
```

## Potential Solution

When a query does `.where_x`, maybe everything in that should be a sub-select?

Doing something like:

```crystal
TodoQuery.new.where_users(UserQuery.new.id(1))
```

Right now would make:

```sql
SELECT todos.*
FROM todos
INNER JOIN users
ON todos.user_id = users.id
WHERE users.id = 1
```

But with subselects would make:

```sql
SELECT todos.*
FROM todos
INNER JOIN (
  SELECT users.*
  FROM users
  WHERE users.id = 1
) as users_temp
ON todos.user_id = users_temp.id
```

(I am not ABSOLUTELY sure those produce the same results as I'm making them up)

**Comment by paulcsmith** [comment]
Thank you for the bug report and the thorough issue. That makes things a lot easier!

**Comment by matthewmcgarvey** [comment]
Getting involved with Avram development seems like my next step so I'm going to try to take a swing at this.

I'm not going to try the sub-select thing I said above. Whether or not it would work, it seems like an involved change. Instead, I'm going to look into checking places before adding a join to see if the table is already accessible. In the error listed above, I would have it not add the join clause because the `FROM` is already accessing `contributors`
