### ISSUE TITLE
Primary key is hard coded in SaveOperation's setup macro

### ISSUE THREAD

**Issue by gaku-sei** [luckyframework/avram#379]
Lucky allows to customize the type of primary key, and the name, which is really handy! But if you happen to use the type UUID, and change the column to something like "uuid" instead of "id", it will raise an error:

<img width="865" alt="Capture d’écran 2020-05-28 à 12 28 35" src="https://user-images.githubusercontent.com/3982371/83095734-f281d400-a0de-11ea-9206-344cd763781e.png">

It seems this line:
https://github.com/luckyframework/avram/blob/bb576790a832b41db10ccf8087fa9a43934a9b6f/src/avram/save_operation_template.cr#L23
Should look like `{{ primary_key_name.id }}.value ||= UUID.random()`

I'd be glad to make a pr if needed  👍

**Comment by jwoertink** [comment]
Ah, good call! Yeah, if you want to do a PR, we're always happy to get those 😄
