### ISSUE TITLE
Add `#new_record?` to Save Operations

### ISSUE THREAD

**Issue by akadusei** [luckyframework/avram#412]
This should return `true` if a new record is being created (or was just created), and false if an existing record is being updated (or was just updated).

In [Shield](https://github.com/GrottoPress/shield/tree/dev), a user may get a notification if their password was changed. However, the notification should **not** be sent if the operation created a new user (rather than updated an existing one). [[reference](https://github.com/GrottoPress/shield/blob/f4167b63b9a17c06b48fc15f69d537521b384f65/src/shield/operations/save_password.cr#L32)]

The method that sends the notification runs in the `after_commit` callback.

There's already `#persisted?`, but that always returns `true` in `after_save` and `after_commit` callbacks, regardless whether we created a new record, or updated an existing one.

I have tried the following approaches:

### 1. Compare `updated_at` with `created_at`

If `updated_at` is greater than `created_at`, the record was updated (rather than created). If they are equal, the record was created (rather than updated).

```crystal
# `after_commit`
def notify_password_change(user : User)
  return unless user.updated_at > user.created_at # <= stop here if not updating existing user
  return unless password_hash.changed?
  # ...
end
```

Even though this works, I feel it is a bug in wait. Looking at the code that sets `updated_at` and `created_at`, it seems the two values were not designed to be equal when a new record is created. [[reference](https://github.com/luckyframework/avram/blob/3fe881faee2da2bc63ae0fed49ecccca1876b0dc/src/avram/save_operation.cr#L326)]

This is because `Time.utc` is called respectively for each of the columns, so the first call could return a time different from the second. If the idea is that they be equal, I would expect that `Time.utc` be captured once into a variable, and that variable used to update both columns, thus:

```crystal
  private def insert : T
    time = Time.utc

    self.created_at.value ||= time if responds_to?(:created_at)
    self.updated_at.value ||= time if responds_to?(:updated_at)
    # ...
  end
```

### 2. Check the previous value of password hash

If `password_hash.original_value` is `nil`, then this was a create operation (rather than an update operation).

```crystal
# `after_commit`
def notify_password_change(user : User)
  return unless password_hash.changed?(from: nil) # <= stop here if not updating existing user
  # ...
end
```

This works, but only because `password_hash` is a non-nilable column. This means the only time the previous password is nil, is when a new user is created.

It should fail if `password_hash` column was nilable.

### 3. Monkey-patch `Avram::NeedyInitializerAndSaveMethods.generate_initializer`

I added a `#new_record?` getter, and updated the `#initialize` methods to set `@new_record` depending on whether or not a `@record : T` parameter exists. [[reference](https://github.com/GrottoPress/shield/blob/f4167b63b9a17c06b48fc15f69d537521b384f65/src/charms.cr#L60)]

It works great, and is my preferred solution. Which is why I think this should be in Avram.

In an operation, regardless of which callback you're in, you can simply call `#new_record?` to check for a create (vs. update).

### 4. Maybe there's a better way to do this?

I'm open to suggestions...

**Comment by paulcsmith** [comment]
I believe what you can do is use the `changed?` method for dirty tracking :D https://luckyframework.org/guides/database/validating-saving#tracking-changed-attributes

```crystal
def maybe_send_password_changed_email(user)
  if encrypted_password.changed?
    # send your email
  end
end
```

The other idea might be to create separate operations for creating and updating. For example you might have a `SignUpUser` and an `UpdateUser` operation. In general I think that is the approach we'd like to promote, rather than adding more logic to existing operations. What do you think? Does this work and make sense for what you're trying to do?

Also, Shield looks cool! I'm gonna take a closer look!

**Comment by akadusei** [comment]
> I believe what you can do is use the changed? method for dirty tracking...

`!encrypted_password.changed?(from: nil)` is as I mentioned in my second point; it works because the column is non-nilable. If the column was nilable, subsequent updates could set it to `nil` and back to some other value, at which point it would pass this check for a newly created record.

> The other idea might be to create separate operations for creating and updating. For example you might have a `SignUpUser` and an `UpdateUser` operation.

This is workable (I haven't tried it yet). That may mean I have to split a number of modules into two modules each (one to create and the other to update), move out common code into their own modules, `include` the common code modules in each of the the modules for create and update, then `include` the resulting modules in `SignUpUser` and `UpdateUser`. Phew!

> What do you think? Does this work and make sense for what you're trying to do?

I already solved it with monkey-patching; it seemed simpler. I may try splitting them out into separate operations.

> Also, Shield looks cool! I'm gonna take a closer look!

I'm sure it does. I would appreciate feedback if you find the time to look.

**Comment by akadusei** [comment]
For anyone looking, you could check if the operation's `id.value.nil?`. For a create operation `id.value` will always be `nil`.

**Comment by jwoertink** [comment]
You can also use `!persisted?` 😃 

```crystal
before_save do
  if !persisted?
    # it's a new record
  end
end
```

**Comment by akadusei** [comment]
> There's already `#persisted?`, but that always returns `true` in `after_save` and `after_commit` callbacks, regardless whether we created a new record, or updated an existing one.

`#persisted?` works only in `before_save`, where record `id` is not set. It returns `true` always in `after_*` hooks, for both create and update operations.
