### ISSUE TITLE
Delete should be an operation

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#413]
Currently, `delete` is a method in `Avram::Model`. It should be an operation. I need a `before` method to check if the user is permitted to delete the object, and if other constraints are satisfied. And after my object is deleted, I need an `after` method to clean up: change object counts I maintain in its parents, make sure nothing references that record's URL, etc. And I don't have access to the same error mechanism used in record creation and updating.

For now, I guess I can hard-code these into my action, but I will have to add a transaction there too. If `delete` was an operation, the transaction,  the callback structure and the error mechanism would be there. There is also the matter of symmetry, currently `delete` is asymmetrical with object creation.

I think this is what he was getting at in https://github.com/luckyframework/lucky/issues/559, filed on Lucky (rather than Avram) two years ago.

I think it also makes sense to access form fields from the delete operation. One can have a "Yes, I know what I'm doing!" field, and a field that says "delete all of the children of this record too", and one can throw the delete operation back to the action asking that the user correct decisions in the forms.

**Comment by BrucePerens** [comment]
@jwoertink Pointed out that I have access to record.delete in an operation that I create. So, not as bad as having to write it into the action. But he hopes to make this more natural in the refactoring he is doing on Avram.

**Comment by akadusei** [comment]
Maybe `SaveOperation` should be split into `CreateOperation`, `UpdateOperation` and `DeleteOperation`, with their respective `before_*` and `after_*` callbacks.

They could have a common interface for calling/running them, like `SomeOperation.run`.

In it's current form, nothing stops anyone from calling `UpdateUser.create`, instead of `UpdateUser.update` (or maybe I don't fully understand Operations yet?).

**Comment by jwoertink** [comment]
@akadusei see https://github.com/luckyframework/lucky/discussions/1209#discussioncomment-32125

**Comment by akadusei** [comment]
@jwoertink Ah, I see. Thanks.
