### ISSUE TITLE
Avram::Database.transaction block return behavior undocumented and may be incorrect

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#416]
`Avram::Database.transaction` wants the transaction block to always return `true`. This is not documented, and is probably a left-over from when someone was designing how the user would roll back the transaction, perhaps returning `false` was considered for initiating a rollback. Obviously we have Avram::Database.rollback to do that today, so the transaction block should have its return value ignored.

**Comment by BrucePerens** [comment]
The problem still exists. Avram::Database#transaction wants the transaction block to return `Bool` here. Nowhere is this documented and I can't see that the return value is put to any use.
```
# :nodoc:
  def transaction : Bool
    if current_transaction
      yield
    else
      wrap_in_transaction do
        yield
      end
    end
  end
```

**Comment by matthewmcgarvey** [comment]
While I _think_ we could work around it, this stems from the `crystal-db` library https://github.com/crystal-lang/crystal-db/issues/145
