### ISSUE TITLE
Lucky `db.create`, `db.reset` fail on some systems because `psql` won't run for the user, or without a database.

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#417]
On my Debian system, security of Postgres may be configured more tightly than other systems. To run `psql` as a normal user (not the Postgres user), a Postgres role must exist for that Unix user AND a database with the same name as the Unix user must exist or an existing database to connect to must be specified with the `-d` argument. This could be the administration database, which is usually `postgres`, but the name of that database is configurable.

So, the Postgres existence test `attempt_to_connect` here fails:
https://github.com/luckyframework/avram/blob/3fe881faee2da2bc63ae0fed49ecccca1876b0dc/src/avram/tasks/db/create.cr#L32-L44

Because that test fails, `lucky db.reset` and `lucky db.create` fail. `lucky db.setup` uses `createdb` and succeeds.

It's probably best to remove the test, or just test that `psql` or `createdb` exist.

**Comment by jwoertink** [comment]
Testing that those exist isn't enough. For example, I use AWS RDS. I have `psql` and `createdb` both installed, but before I can run `createdb` on that engine, I need to know if I even have the ability to do so. The only way to do this is by seeing if I can actually log into `psql` with the given permissions. In this case, I don't have a database yet, so I can't specify a database name.

Let me make sure I understand correctly here though:

* debian user is "jeremy"
* postgres user is "dbdude"

If I ran `psql -U dbdude -h localhost` then I would be logged in to psql. Are you saying that in your case, this doesn't work? Or can you provide an example of some fake usernames so I can better see how you have it setup?

**Comment by BrucePerens** [comment]
There is a .pgpass file providing the password.
```
bruce@nuc:~/Crystal/UserCorps/usercorps$ psql -U usercorps -h localhost
psql: FATAL:  database "usercorps" does not exist
bruce@nuc:~/Crystal/UserCorps/usercorps$ !! -d postgres
psql -U usercorps -h localhost -d postgres
psql (11.7 (Debian 11.7-0+deb10u1))
SSL connection (protocol: TLSv1.3, cipher: TLS_AES_256_GCM_SHA384, bits: 256, compression: off)
Type "help" for help.
```

**Comment by BrucePerens** [comment]
This works without providing a hard-coded database name:
```
psql -U usercorps -h localhost --list
```

**Comment by BrucePerens** [comment]
psql (really pg_wrapper) is a perl program. It isn't doing anything we can't do from Crystal. Perhaps the best solution is just to connect to the `postgres` db, and allow it to be configured if the name of the management db is something else.

**Comment by jwoertink** [comment]
oh, I see what you're saying. I just tried the same thing, and got the same error, but in the command above we use the `--list` flag which doesn't give me the error.

```
[15:08PM] sandbox$ psql
psql: FATAL:  database "jeremywoertink" does not exist
[15:09PM] sandbox$ psql -l
                                               List of databases
```

Where I do have a `jeremywoertink` user in postgres, but no database by that name. And if we try one that's invalid..

```
[15:09PM] sandbox$ psql -l -U doesnotexist
psql: FATAL:  role "doesnotexist" does not exist
```

I think I'm gonna just rip this out anyway. There's a few refactors I want to do where we can just use raw SQL instead of using the client tools to do all of this.

**Comment by BrucePerens** [comment]
Yes. Use raw SQL, allow configuration to set the management database name, with its default as "postgres".

Consider that your Crystal application is not really bound to run on top of a command-line environment. As we use things like AWS, that makes a lot more sense. Reduce the attack surface, etc.
