### ISSUE TITLE
Stray newline in config results in creating extra database

### ISSUE THREAD

**Issue by digitalcora** [luckyframework/avram#423]
Starting a new Lucky project, since my database username defaulted to my OS username rather than `"postgres"`, I replaced the appropriate line of the generated `config/database.cr` as follows (for some reason it went over my head that `.env` would be a better way to do this):

```crystal
settings.url = ENV["DATABASE_URL"]? || Avram::PostgresURL.build(
  database: database_name,
  hostname: ENV["DB_HOST"]? || "localhost",
  port: ENV["DB_PORT"]? || "5432",
  username: ENV["DB_USERNAME"]? || `whoami`, # <= oops! spot the mistake
  password: ENV["DB_PASSWORD"]? || ""        # <=
)
```

I then ran `lucky db.create` and got a very weird error (this was after manually fixing #422):

```
Unhandled exception: --: 2: --: -h: not found
 (Exception)
  from lib/avram/src/avram/migrator/runner.cr:126:7 in 'run'
  from lib/avram/src/avram/migrator/runner.cr:65:5 in 'create_db'
  from lib/avram/src/avram/tasks/db/create.cr:24:7 in 'call'
  from lib/avram/src/avram/tasks/db/create.cr:1:1 in 'print_help_or_call'
  from lib/lucky_cli/src/lucky_cli/runner.cr:27:9 in 'run'
```

Despite the error a database was created, but named after my username, instead of `myapp_development` as expected!

After some source diving, I figured out where I'd made a misstep. The backticks around `whoami` also capture the newline at the end of the command's output, splitting Avram's `createdb` command line into two separate commands:

```
createdb -U cora
 -h localhost -p 5432 myapp_development
```

The first line is treated as equivalent to `createdb cora`, and the second line generates the `-h: not found` error.

Fortunately `dropdb -U cora` (and similar) gives an error, so it's a bit harder to destroy data you weren't expecting to with `lucky db.drop`. Still, the current behavior gives a very obscure error, and also silently creates an extra unwanted database. Maybe these config values need to be rendered "shell-safe" before inserting them into a command line.

**Comment by jwoertink** [comment]
lol. Nice bug find. I know we have `shell: true` on that [process](https://github.com/luckyframework/avram/blob/master/src/avram/migrator/runner.cr#L120), but we should for sure trim up each [of these inputs](https://github.com/luckyframework/avram/blob/master/src/avram/migrator/runner.cr#L15). It's probably a safe assumption that no one's username, pw, host, etc... would have a space or newline at either side 😅

**Comment by digitalcora** [comment]
That'd definitely fix the line-splitting issue, although e.g. having a stray ampersand in the wrong place (admittedly a less likely scenario than a line break) will cause the same problem:

```shell
# creates a database named `cora` and crashes with "--: 1: --: -h: not found"
createdb -U cora& -h localhost -p 5432 myapp_development
```

Other shell special characters like `"` can cause strange errors, but at least won't create an extra database:

```shell
# crashes with "--: 1: --: Syntax error: Unterminated quoted string"
createdb -U cora" -h localhost -p 5432 myapp_development
```

Looking around, it seems there's a function [`Process.quote`](https://crystal-lang.org/api/0.35.1/Process.html#quote(arg:String):String-class-method) that's meant to help with this when using `shell: true`. Although, _is_ it necessary to use `shell: true` in this case? i.e. would there be anything wrong with:

```crystal
Process.run("createdb", ["-U", "cora", "-h", "localhost", "-p", "5432", "myapp_development"])
```

**Comment by digitalcora** [comment]
FWIW, I tried running this in a test file, simulating the newline issue but without `shell: true`:

```crystal
Process.run("createdb", ["-U", `whoami`, "-h", "localhost", "-p", "5432", "myapp_development"])
```

and it fails with:

```
2020-07-12 11:20:52.048 EDT [6841] FATAL:  role "cora
        " does not exist
```

The error message comes out a bit odd, but no extra database is created, and it's a bit clearer what the problem is. Shell special characters aren't an issue this way, so if you really want your database to be named `myapp_dev&test`, more power to you 😄 (this actually is a valid Postgres database name, but would be un-creatable with Avram right now)

**Comment by digitalcora** [comment]
The linked PR #433 does solve this issue specifically with regard to newlines (or other whitespace), but since the code that runs the `createdb` command is still using `shell: true` and its inputs are not being shell-quoted, I think the issue would still occur if other shell special characters appear in the database name, as I outlined in the previous comments. For example, `me&you` is a valid Postgres database name, but using this name in Avram will instead create a database named `me` and then crash. I can create a separate issue for this, if desired.

**Comment by paulcsmith** [comment]
@digitalcora ah yes that makes sense! A separate issue would be wonderful. Thanks for your help and the explanation!
