### ISSUE TITLE
Add Ameba

### ISSUE THREAD

**Issue by igor-alexandrov** [luckyframework/avram#431]
I tried to run Ameba locally and here is what I got:

```
Finished in 795.01 milliseconds

257 inspected, 74 failures.
```

What do you think about added Ameba to Avram?

**Comment by jwoertink** [comment]
I've wanted to add it in for a while now, just haven't got around to it. I know I've talked with @paulcsmith about that before, and he mentioned the same. If you wanted to submit a PR with it in, that'd be cool. Just make sure it's set as a development_dependency 👍

**Comment by igor-alexandrov** [comment]
Will do tomorrow. @paulcsmith  @jwoertink how do you feel about running Ameba in GitHub Actions together with code formatting?

**Comment by jwoertink** [comment]
Oh yeah, for sure. There's actually an ameba action out there. Maybe we just use that? https://github.com/crystal-ameba/github-action

**Comment by igor-alexandrov** [comment]
Sure, I will try.
