### ISSUE TITLE
Create proxy for working with crystal-db without calling crystal-db 

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#435]
Instead of

```crystal
AppDatabase.run do |db|
  db.query "whatever"
end
```

It could be

```crystal
AppDatabase.query "whatever"
```

This is:

* More concise
* And allows us to do fancy stuff like logging and instrumentation with Pulsar https://github.com/luckyframework/pulsar. This means you can send metrics, use with Breeze, etc.

**Comment by jwoertink** [comment]
This was done in https://github.com/luckyframework/avram/pull/441
