### ISSUE TITLE
Issues with database config values containing shell special characters

### ISSUE THREAD

**Issue by digitalcora** [luckyframework/avram#440]
This is a follow-on from #423.

Avram runs `createdb` and `dropdb` commands by string-concatting the config values into a command line, which is passed to `Process.run` with `shell: true`. This means the presence of shell special characters in these values can result in crashes or unintended consequences, e.g. creating/dropping a database other than the one specified.

Examples (these use the database name, but the issue applies to all config values):

* Naming your database `cora"` will crash with the error `--: 1: --: Syntax error: Unterminated quoted string`
* Naming it `good&true` will appear to work, but instead create/drop a database named `good` (with no environment suffix)
* Naming it `#blessed` and creating it will appear to work, but instead create a database with the same name as the current user (the default if no database name is given to `createdb`)

Taking a glance over [the code that calls `Process.run`](https://github.com/luckyframework/avram/blob/998ee826d7674f04ec683d5f9f63395e5b3afadf/src/avram/migrator/runner.cr#L119), it's unclear to me why `shell: true` would be required here, and it seems like it could be easily rewritten without:

```crystal
# using shell
Process.run("createdb -U user -h hostname ...", shell: true)

# using argv
Process.run("createdb", ["-U", "user", "-h", "hostname", ...])
```

But if `shell: true` is necessary for reasons I'm not seeing, each argument could be escaped using [`Process.quote`](https://crystal-lang.org/api/0.35.1/Process.html#quote(args:Enumerable(String)):String-class-method).

**Comment by paulcsmith** [comment]
I am not very familiar with the `Process` library so it is very likely that `shell: true` is not needed, and may have been done for convenience (not needing to break out the args). If you have time to submit a PR switching it to argv that'd be great, but if not we can use Process.quote in the meantime.

Thanks for the thorough issue. That was super helpful!

**Comment by paulcsmith** [comment]
Haha good point! Thanks for the help with this @digitalcora
