### ISSUE TITLE
Boolean field with no default value generate an error when saving a operation

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/avram#445]
Hello, just found this bug:

When field is boolean and the record.field is false, this would overwrite the value with the default or generate an error if no default value

https://github.com/luckyframework/avram/blob/5e94a193b2195932b9a27896f598cb447372bd19/src/avram/save_operation.cr#L126

I changed that line to:

```crystal
value: @record.try(&.{{ attribute[:name] }}).nil? ? default_value_for_{{ attribute[:name] }} : @record.try(&.{{ attribute[:name] }}),
```

I was going to make a PR, but I don't quite understand how is tests organized in that part

So just wanted to let you know about this, if others encounter the same problem

**Comment by paulcsmith** [comment]
Hi @Xosmond this is fixed in master. In the next release you can set a default in your model and it will be set in the operation for you automatically :D
