### ISSUE TITLE
Unique constraint on the migrations table

### ISSUE THREAD

**Issue by brunto** [luckyframework/avram#446]
I think we must add the unique constraint to the "version" column to avoid duplicate versions error:
https://github.com/luckyframework/avram/blob/998ee826d7674f04ec683d5f9f63395e5b3afadf/src/avram/migrator/runner.cr#L114

**Comment by paulcsmith** [comment]
Good idea!

**Comment by brunto** [comment]
Ok, I'll create a PR today.

**Comment by brunto** [comment]
I need to add a simple test.

**Comment by jwoertink** [comment]
Fixed by https://github.com/luckyframework/avram/pull/815
