### ISSUE TITLE
Empty field for type Time is invalid.

### ISSUE THREAD

**Issue by brunto** [luckyframework/avram#447]
I have a table with this column `column date_certif : Time?` and action with a save query `agency = SaveAgency.create!(params)`

When I pass a param like `agency:date_certif=2020-08-01`, everything works great but, when I try to empty the column like this `agency:date_certif=""` I have the following error `date_certif: is invalid`.
It’s invalid because date_certif only accepts `Time | Nothing | Nil`.

For now to fix this I must do:
```
date_certif = params.get?("agency:date_certif")
date_certif = date_certif && date_certif.present? ? Time.parse_local(date_certif, "%F") : nil
agency = SaveAgency.create!(params, date_certif: date_certif)
```

**Comment by paulcsmith** [comment]
Thanks for the thorough bug report @brunto! And thanks for the workaround in case others run into this while we get this fixed
