### ISSUE TITLE
Confusing error when trying to use a nilable attribute

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#466]
I created a regular `Avram::Operation`, and set an attribute type to nilable

```crystal
class DoThing < Avram::Operation
  attribute prop : String?

  def submit
    #...
  end
end
```

Then I got this error message (with full `--error-trace` on)

```

 1 | require "./start_server"
     ^
Error: while requiring "./start_server"


In src/start_server.cr:1:1

 1 | require "./app"
     ^
Error: while requiring "./app"


In src/app.cr:7:1

 7 | require "./operations/**"
     ^
Error: attribute must use just one type
```

I think we can make [this error](https://github.com/luckyframework/avram/blob/master/src/avram/define_attribute.cr#L39) better. It should at least point to the Type.

**Comment by matthewmcgarvey** [comment]
And it also seems weird to limit it to one type. Maybe we can update the macro to make sure that it's not nilable but it can be anything else?

**Comment by jwoertink** [comment]
I think if we allow for a union, it makes the compiler start to get wonky. Like if someone did `attribute thing : Int32 | Array(String)`, then you would get weird errors like "no method join for Int32 compile-time Int32 | Array(String)". Considering this is data that comes in from a param source, we should probably just enforce that it's only the one type.

**Comment by robacarp** [comment]
Keeping out unions makes sense to me, and I see why it's written as such in the code. Params _can_ be missing if the html form isn't written correctly, or data isn't filled out. That's what `validate_required` is for. 

When you start to use an operation from a non-http context (ie some background worker), manually you don't want to build an Avram::Params object just to pass in a nilable source, and marking an attribute as nilable is the a go-to. (The paradigm of a nilable `need` leads me to think that a param should also be allowed to be nilable)

**Comment by jwoertink** [comment]
It's definitely a little confusing because we have several different formats for allowing data to come in, but with slightly different purposes. 

I think for this issue, we can do something like this

```crystal
# maybe check if the union has Nil?
raise <<-ERROR
Defining a nilable attribute like {{ type_dec.type }} is not needed.
All attributes are considered nilable by default.

Try this...
   {{ better_example }}

Read more on attributes "link to website"
ERROR
```

That way we can just guide people to understand that these are always considered nilable, and point to some good docs on it.
