### ISSUE TITLE
Naming associations something other than the model causes issues

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#473]
It sometimes makes sense to name an association something other than the model name it points to. For example, you might have a `Book` model and it makes more sense for it to have and `author` than just a `user`. When this is done with Avram models, it can cause issues because we assume the table from the variable name in some places and use the underlying table name to generate code in others which creates a confusing and sometimes broken api.

It is possible to pass a `table_name` flag with this appropriately named table to a `belongs_to` relationship but it is undocumented and confusing. I believe that each association should use the given association name where ever possible and delegate to class methods on the provided type where the association name won't work.

- [ ] Fix belongs_to
- [ ] Fix has_many
- [ ] Fix has_one

### has_many

When declaring a has_many relationship with a custom name, the generated join method is still using the table name instead of the given association name.

```crystal
class Boss < BaseModel
  table do
    has_many employees : User
  end
end
```

The generated join should result in queries being made like this:

```crystal
BossQuery.new.where_employees(UserQuery.new.name("asdfasf"))
```

but it produces a compilation error because the underlying `inner_join_xxx` methods use the table name.

**Comment by jwoertink** [comment]
Does this still happen if you specify a table on those? `table :users` and `table :books`?

**Comment by matthewmcgarvey** [comment]
ahhh, I didn't know that there was an api for that.  It doesn't seem like that is necessary though if we switch to calling the class method
