### ISSUE TITLE
postinstall creates a bin directory two folders up from project

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#475]
[postinstall in shard.yml](https://github.com/luckyframework/avram/blob/b072877c2b6c581ce08bdf950e1627d2e39dc4b7/shard.yml#L45) runs [script/precompile_tasks](https://github.com/luckyframework/avram/blob/master/script/precompile_tasks) which makes a `bin` directory two directories above the current location. I think this was assuming that the script would run in the context of the avram directory and two directories up would be the project it's installed in but it is running in the project directory which means it is going to directories above that.

Because it has most likely never worked, and it is a bit of a wait, I wouldn't mind seeing it removed.

**Comment by matthewmcgarvey** [comment]
this bug is also in lucky https://github.com/luckyframework/lucky/blob/8ca0211fba3fbf88598edeb16aabd7ca9ffdaaed/script/precompile_tasks#L7

**Comment by jwoertink** [comment]
I'm not sure I understand the issue here. Anytime I've installed Avram, the postinstall has always put the `bin` directory where I've needed it. Are you saying that you're getting a random `bin` directory somewhere else on your computer?

**Comment by matthewmcgarvey** [comment]
I am finding bin folders coming from a lucky library two directories up from where I keep them but I'm not able to reproduce it after all. I will close this for now

**Comment by jwoertink** [comment]
That's strange. I just tried too, and didn't get it. If you do figure out what's causing it, feel free to reopen.
