### ISSUE TITLE
Add ability to add a unique index when using add_belongs_to in a migration

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#482]
In order to have a reliable "has one" relationship, it makes sense to put a unique index on the belongs to relationship table but there is currently no way to do that.

`unique: true` should be added to the index creation in both macros

https://github.com/luckyframework/avram/blob/69e61d66fa0b2bcb53109a5a516904d0ea1afa21/src/avram/migrator/create_table_statement.cr#L134

https://github.com/luckyframework/avram/blob/69e61d66fa0b2bcb53109a5a516904d0ea1afa21/src/avram/migrator/alter_table_statement.cr#L111

This would be used like this: `add_belongs_to author : User, unique: true`

**Comment by paulcsmith** [comment]
Good idea! Edited the title a bit to clarify what the issue needs to be closed
