### ISSUE TITLE
New wrap_query method

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#488]
With the new https://github.com/luckyframework/avram/pull/442 OR queries added in, it's possible you could create some complex queries that will return the wrong data. In some cases you may need to group your conditions by wrapping them in parenthesis. We need to add a new method that will allow us to group these conditions and wrap them in parenthesis.

```crystal
# WHERE (name = 'Bill' OR name = 'Bob')
UserQuery.new.where(&.name("Bill").or(&.name("Bob")))
```

**Comment by matthewmcgarvey** [comment]
Maybe there could be a `#where` that yields like the `#or` method?

The other thing to consider is whether or not calling `#or` applies to the previous statement or all of the previous conditions. Does calling `UserQuery.new.name("Bill").age(19).or(&.age(28))` turn into:
```sql
SELECT *
FROM users
WHERE (name = 'Bill' AND age = 19)
  OR age = 28;
```

or does it turn into:
```sql
SELECT *
FROM users
WHERE name = 'Bill'
  AND age = 19
  OR age = 28;
```

because those are two different sql statements.  I check in Rails and it does the seconds and we currently do that as well.

**Comment by matthewmcgarvey** [comment]
They might not be different, actually. Precedence is so confusing 🤯🤯🤯

**Comment by jwoertink** [comment]
Currently we do not add parenthesis. The idea of this method would be that it places it where you need. There was another ORM I was looking at that did this. I thought it was laravel, but now I can't find it 😕 

In any case, I think it would be like this:

```sql
--UserQuery.new.name("Bill").age(19).or(&.age(28))
 
SELECT *
FROM users
WHERE name = 'Bill' AND age = 19 OR age = 28;

--UserQuery.new.name("Bill").wrap_query(&.age(19).or(&.age(28)))
 
SELECT *
FROM users
WHERE name = 'Bill' AND (age = 19 OR age = 28);
```

and yes, precedence is super confusing 😅

**Comment by paulcsmith** [comment]
The Laravel one is here: https://laravel.com/docs/8.x/queries#parameter-grouping

They just call it `where` and it groups them when you pass a function (block in Crystal). Maybe can use that and call it `where` since I think `wrap_query` sounds like it is wrapping a whole query or something.

I'd be down to explore alternatives though! Maybe `group_criteria`? That seems clear but I'm not sure

```crystal
UserQuery.new.admin(true).group_criteria(&.name("Paul").or(&.name("Jeremy"))
```

**Comment by jwoertink** [comment]
I know when we talked about this before we initially jumped at calling it "group" but quickly realized that `group` is taken for the GROUP BY stuff... I just don't want to get people confused between those two.

Here's a few names...
```crystal
UserQuery.new.admin(true).group_criteria(&.name("Paul").or(&.name("Jeremy"))
UserQuery.new.admin(true).wrap_criteria(&.name("Paul").or(&.name("Jeremy")))
UserQuery.new.admin(true).where(&.name("Paul").or(&.name("Jeremy")))
UserQuery.new.admin(true).condition(&.name("Paul").or(&.name("Jeremy")))
UserQuery.new.admin(true).parenthesis(&.name("Paul").or(&.name("Jeremy")))
```

**Comment by paulcsmith** [comment]
I actually kinda like `where`. Since you give it a block I think it makes sense. And yeah good point about avoiding "group" in this context

**Comment by jwoertink** [comment]
I'm cool with using where with the block. I think that's easy enough.

**Comment by stephendolan** [comment]
Thought I'd pop in a real-world example I ran into today regarding this. At https://luckycasts.com/videos, I have an optional search param that looks at video titles, descriptions, and topics. Currently, I have to duplicate the `published_at.lte(Time.utc)` part in every `OR` clause to ensure that non-published videos aren't returned:

```crystal
class Videos::Index < BrowserAction
  param q : String?
  param topic : String?

  get "/videos" do
    authorize

    html Videos::IndexPage, videos: videos, search_query: q
  end

  private def videos
    query = VideoQuery.new.published_at.lte(Time.utc)
    query = preload_associations(query)
    query = search_by_query(query)
    query = search_by_topic(query)
    apply_ordering(query)
  end

  private def preload_associations(query) : VideoQuery
    query.preload_author
      .preload_difficulty_level
      .preload_topics
  end

  private def apply_ordering(query) : VideoQuery
    query.published_at.desc_order
  end

  private def search_by_query(query) : VideoQuery
    return query unless (search_query = q)

    wildcard_search = "%#{search_query}%"

    query.title.ilike(wildcard_search)
      .or(&.description.ilike(wildcard_search).published_at.lte(Time.utc))
      .or(&.left_join_topics.where_topics(TopicQuery.new.label.ilike(wildcard_search)).published_at.lte(Time.utc))
      .group(&.id)
  end

  private def search_by_topic(query) : VideoQuery
    return query unless (topic_query = topic)

    query.where_topics(TopicQuery.new.label(topic_query))
  end
end
```

Big fan of the `.where` syntax proposed above!

**Comment by da1nerd** [comment]
I was stumbling around this recently and my immediate assumption was that there's got to be a `.where` syntax that does what I want. Using `.where` is very intuitive in my opinion.
