### ISSUE TITLE
Compiler error when defining has_many through a has_many relationship

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#496]
https://github.com/luckyframework/avram/blob/dddcf7d4002ac51cbc12b36d15574ca5ee11989a/src/avram/associations/has_many.cr#L90

https://github.com/luckyframework/avram/blob/dddcf7d4002ac51cbc12b36d15574ca5ee11989a/src/avram/associations/has_many.cr#L114

Both of these lines (and maybe more) expect the target association to have a `#preload_xxx` method that matches the "through" name. So in a code example like

```crystal
class Sale < BaseModel
  table do
    belongs_to employee : Employee
  end
end

class Employee < BaseModel
  table do
    has_many sales : Sale
    belongs_to manager : Manager
  end
end

class Manager < BaseModel
  table do
    has_many employees : Employee
    has_many sales : Sale, through: :employees
  end
end
```

Trying to call `manager.sales` with lazy loading enabled causes a compilation error like

```
Showing last frame. Use --error-trace for full trace.

There was a problem expanding macro 'define_has_many_lazy_loading'

Code in macro 'has_many'

 19 | define_has_many_lazy_loading(sales, Sale, manager_id, :employees)
      ^
Called macro defined in src/avram/associations/has_many.cr:72:11

 72 | private macro define_has_many_lazy_loading(assoc_name, model, foreign_key, through)

Which expanded to:

 > 39 |   through_query.manager_id(id)
 > 40 | end
 > 41 | .preload_employees
         ^----------------
Error: undefined method 'preload_employees' for Sale::BaseQuery

Did you mean 'preload_employee'?
```

**NOTE**: this is the first error I ran into when trying to define a has_many through a has_many association. There could be more after this oen.

**Comment by jwoertink** [comment]
related: https://github.com/luckyframework/avram/issues/196
