### ISSUE TITLE
Allow setting a default value for a column

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#5]
Maybe something like this:

```crystal
column admin : Bool = false
```

Or should it get it from the database automatically? My thought is that it shouldn't because we're manually defining everything else so it would be weird to have Lucky magically set up a default.

It should probably warn or raise if you forget to the declare the default and there is a default at the database level though.

**Comment by russ** [comment]
I think works now? I tested using `autogenerated` and it worked as I expected it too.

`column my_field : Bool, autogenerated: true`

That let me save my record and it used the default value from the database schema.

**Comment by paulcsmith** [comment]
@russ Honestly I had not thought of doing that! That solves part of this, but then in your operations you'd still have a `nil` until the record is saved. I'm thinking you should be able to set a default value in the `column` definition and then in your operations it uses that as the default field value.

I did open an issue on the website repo to document the `autogenerated` part since that gets us pretty close!

**Comment by russ** [comment]
I thought about that a lot and talked with @jwoertink about it. It's not the best case to have to deal with nil's at that level but I felt that was a fair trade off with the setup that this has. I also really couldn't think of to many situations it would even come up.

**Comment by jwoertink** [comment]
This is added in https://github.com/luckyframework/avram/pull/424
