### ISSUE TITLE
bind message supplies 2 parameters, but prepared statement "" requires 1

### ISSUE THREAD

**Issue by edwardloveall** [luckyframework/avram#51]
I'm having trouble tracking this bug down. Here's a `crystal play` session you can run, as long as you have a database with two tables `users` and `follows`:

```
users   (id, created_at, updated_at)
follows (id, created_at, updated_at, from_id)
```

```crystal
require "avram"

Avram::Repo.configure do |settings|
  settings.url = "postgres://localhost/linkybits_development"
end

class User < Avram::Model
  table users do
  end
end

class Follow < Avram::Model
  table follows do
    belongs_to from : User
  end
end

user = User::BaseQuery.new.first
follows = Follow::BaseQuery.new.preload_from

if !follows.size.zero?
  follows.each do |follows|
    # anything
  end
end
```

The error is just above `# anything`:

> bind message supplies 2 parameters, but prepared statement "" requires 1

Any idea?

**Comment by paulcsmith** [comment]
What is the SQL the it is running? Could you get it (with `to_sql`) and post it here?

**Comment by edwardloveall** [comment]
I also just found that if you replace the `if` block stuff at the end with `follows.includes?(follows.first)` it has the same error. Perhaps something to do with enumerable?

**Comment by paulcsmith** [comment]
Could you link to the code you’re taking about? I’m not sure I follow. Also have you been able to add a failing spec? That would be super helpful if you can boil it down to something reproducible in spec form.

**Comment by edwardloveall** [comment]
Here's the PR to look at: https://github.com/edwardloveall/lucky_bits/pull/30

I'm actually going to close it soon in favor of a different feature, but it still shows the issue. I haven't been able to make it into a spec. Let me try that!

**Comment by edwardloveall** [comment]
@paulcsmith would you be interested in pairing on this? I have a decent amount of time this weekend

**Comment by paulcsmith** [comment]
I’m definitely interested. I may have time tomorrow. I’ll ping ya on Gitter though when I know for sure!

**Comment by edwardloveall** [comment]
I made a little progress on this today. In `src/avram/queryable.cr#exec_query` the `query.args` _do_ contain two arguments where the query only asks for one.

Query:
```sql
SELECT managers.id, managers.created_at, managers.updated_at, managers.name FROM managers WHERE managers.id = ANY ($1)
```

Arguments:
```
[[], []]
```

Still trying to track down why two are added instead of one.
