### ISSUE TITLE
There's no reason to have both Avram::Query and Avram::Queryable

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#510]
Right now the `Avram::Query` abstract class does almost nothing but `Avram::Queryable` depends on the few methods that it provides. I believe it makes sense to merge all of the functionality in it into `Avram::Queryable` and to remove the class.

**Comment by paulcsmith** [comment]
I think since only internal code references this it would not be difficult to do post 1.0 so I'll remove that, but feel free to add it back if I missed something and users/external libs do depend on these classes
