### ISSUE TITLE
crystal-pg uuid support seems to break some specs

### ISSUE THREAD

**Issue by bcardiff** [luckyframework/avram#511]
I got this trace while checking crystal-pg master via test-ecosystem. The UUID support has been added in 0.22.0, which is the version stated in shard.yml. 0.22.1 was already released with some fixes of 0.22.0's shard.yml. I'm not sure if that could have make this go undetected.

In https://github.com/will/crystal-pg/pull/209 the return type for .read operations over a UUID column is changed from String to UUID which is consistent with the error trace below.

I would have expected that https://github.com/luckyframework/avram/blob/master/src/avram/charms/uuid_extensions.cr#L10 would allow this to go smoothly, but it seems I am missing some wiring in the middle.

```
#   2) Avram::SaveOperation callbacks runs before_save in parent class and before_save in child class
# 
#        PG::ResultSet#read returned a UUID. A String was expected. (Exception)
#          from lib/db/src/db/result_set.cr:80:7 in 'read'
#          from spec/support/line_item.cr:4:3 in 'initialize'
#          from spec/support/line_item.cr:4:3 in 'new'
#          from spec/support/line_item.cr:4:3 in 'from_rs'
#          from src/avram/save_operation.cr:331:19 in 'insert'
#          from src/avram/save_operation.cr:312:7 in 'insert_or_update'
#          from src/avram/save_operation.cr:268:9 in 'save'
#          from spec/save_operation_callbacks_spec.cr:66:9 in '->'
#          from ../../../crystal/src/primitives.cr:255:3 in 'internal_run'
#          from ../../../crystal/src/spec/example.cr:33:16 in 'run'
#          from ../../../crystal/src/spec/context.cr:18:23 in 'internal_run'
#          from ../../../crystal/src/spec/context.cr:330:7 in 'run'
#          from ../../../crystal/src/spec/context.cr:18:23 in 'internal_run'
#          from ../../../crystal/src/spec/context.cr:147:7 in 'run'
#          from ../../../crystal/src/spec/dsl.cr:274:7 in '->'
#          from ../../../crystal/src/primitives.cr:255:3 in 'run'
#          from ../../../crystal/src/crystal/main.cr:45:14 in 'main'
#          from ../../../crystal/src/crystal/main.cr:114:3 in 'main'
#          from __libc_start_main
#          from _start
#          from ???
```

**Comment by jwoertink** [comment]
That's strange... Are you pulling from Avram master? This was an error we were getting, but I had made the change on https://github.com/luckyframework/avram/blob/master/src/avram/charms/uuid_extensions.cr#L7 from `String` to `UUID` which (I thought) fixed this error 🤔

**Comment by bcardiff** [comment]
My bad, I was checking against avram@0.16.1. I'll close for now.

**Comment by jwoertink** [comment]
ah! Ok. Yeah, we haven't released yet, but if you still notice issues off master, let us know! Thanks 😄
