### ISSUE TITLE
Update how we define has many through relationships

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#523]
Related: https://github.com/luckyframework/avram/issues/496
Related: https://github.com/luckyframework/avram/issues/196

## Intro

When we define a has many through relationship, we assume that the intermediary "through" relationship has a foreign key pointing at the final table. So a `has_many customers : Customer, through: :employees` comes with the assumption that the employee model has a belongs to relationship to customers. That could be a sensible requirement. [AdonisJS's ORM](https://preview.adonisjs.com/guides/model-relations/has-many-through/) requires has many through relationships to be defined in this way.

## Problem

The problem is that we would like to support all has many through relationships in Avram and has many through relationships can also be defined where the intermediary has a has many relationship to the final table. The problem with has many through associations is that the association name given to them on the base model is not necessarily the same name as the name given to it on the intermediary model. In the example above, `has_many customers : Customer, through: :employees`, the intermediary `Employee` model could have a `has_many customers : Customer` relationship or a `belongs_to customer : Customer` relationship. The difference between the two is pluralization. The question is, though, how do we know in the base/source model which association type it is on the intermediary model? We can't inspect the associations to find out because of our current way of code generation which means there's no clear compile time way of determining how to interact with the intermediary model.

### Use a macro to pluralize/singularize the association and use `responds_to?` at runtime

This is definitely my least favorite solution and will make quite a mess in the codebase. The idea would be that we would pass around the association name of "customers" and we would singularize it into "customer" and use if blocks where we call `if @association.responds_to?(singular_name)` to determine the right methods to call.

I don't like it because of how likely we are to get the wrong name and that it creates runtime checks where we have had compile time safety.

### Remove the ability to define has many through a has many relationship

This could be an option, but I don't know how we would implement it. As I said above, we cannot inspect other models to determine at compile-time what the associations are.

### Remove the ability to define has many through relationships

While this might sound silly, Diesel, the most popular rust ORM, [only allows belongs to relationships](https://docs.diesel.rs/diesel/associations/index.html) so it is not unheard of to limit associations.

### Separate Queries from Models

This would allow us to inspect models when generating the code for queries and determine relationships more confidently. This would be a significant change to the codebase and have a lot of implications outside of this narrow issue.

### Require the associations names to be defined for the relationship

[This is how Ecto (elixir) does their has many through relationships](https://www.notion.so/Avram-Associations-Notes-ff0e880e9c5e492aaef68443e26776ba#b84cad0e1fa84ee4bdf5bcbf56c64484). Rather than declaring `has_many customers : Customer, through: :employees` and Avram has to guess on how to go from Employee to Customer, users would declare it like `has_many customers : Customer, through: [:employees, :customers]` and the array is the method list that we use to get to customers.

I definitely like this solution this best. While it would still be a breaking change, it would be a simple one and it would solve this issue entirely.

**Comment by jwoertink** [comment]
I think I would be ok with removing the has many through completely if we just had lots of examples on how to achieve the same result outside of the definition. But I do really like the `through: [:employees, :customers]`. With that one, would it be possible to have that be `through: {Employee, Customer}` for the type safety? A chain of models in a tuple (or array) that we can dig down... If not, I get it, but that would be pretty neat!

**Comment by matthewmcgarvey** [comment]
We wouldn't get any more type safety either way because we can't resolve model types in a model. The plan with the `through: [:employees, :customers]` is that they are reduced over and directly macro'd onto method names (`where_emplyees`, `where_customers`)

**Comment by edwardloveall** [comment]
@matthewmcgarvey and I paired on this a bit and he walked me through it. I agree with @jwoertink that the `through: []` is a nice way of solving it without over-complecating the interface for developers. I say spike it out and see how the code looks.

**Comment by matthewmcgarvey** [comment]
While there is an issue with the joins for queries, the more difficult problem to solve is actually in the preloads and not fixed by the array solution. https://github.com/luckyframework/avram/blob/db5722a2ad9ad2d3be769aa627168ba69b4c943d/src/avram/associations/has_many.cr#L46

From the has many association, we preload the intermediary association in order to group the results to put them on the correct base association. I believe the solution would be to return the has many association resulting sql with the base association's id included but I'm not sure Avram has the ability to accomplish that right now.
