### ISSUE TITLE
Allow for custom errors on operations

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#529]
I want to be able to do my own custom validation and error against a non column.

```crystal
class SaveMessage < Message::SaveOperation
  needs author : User
  permit_columns text

  before do
    if author.banned?
      add_error(:author_banned, "You've been banned from posting messages.")
    end 
   end
end
```

**Comment by matthewmcgarvey** [comment]
I also had a use case where I wanted to make an operation invalid or needed to skip saving but was disappointed when I found out that it was directly tied to the column attributes... but I can't seem to remember it right now 🤷

**Comment by matthewmcgarvey** [comment]
O wait! I think I was using nested save operations and wanted to add an error to the parent operation if a child op failed. In rails I would have added an error to the `:base` attribute but there isn't one for Avram. (I _think_ that was the use case)

**Comment by jwoertink** [comment]
Yeah for sure! We had that `@valid` instance variable floating around there doing nothing. Lets put it back in and put it to use! Then at any point you can just set it to false and kick out.
