### ISSUE TITLE
Issues with preloads

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#531]
I'm building an app against master, and I'm running in to a lot of issues with preloading. Way more than I've ran into before, so something must have changed recently, but I'm not sure what. I'm currently unable to use any method generated from an association because they all require preloading. The issue is that once these methods are created, you no longer have access to the underlying query to be able to preload them.

This is the most recent one I got:

```crystal
class MessageSerializer < BaseSerializer
  def initialize(@message : Message)
  end

  def render
    {
      text: @message.text,
      message_id: @message.id,
      username: @message.user.username
    }
  end
end
```

> user for Message must be preloaded with 'preload_user'

In this case `Message` `belongs_to user : User`, and `User` `has_many messages : Message`. Just calling `message.user` throws the error. 

To get around this, I have to now create a `user` method in my `Message` model that will build out the query with the preload.

```crystal
class Message < BaseModel
  table do
    column text : String
    column user_id : Int64
  end

  def user
    UserQuery.find(user_id)
  end
end
```

By doing this, it makes the `belongs_to` useless. I'm having this same issue when it comes to the `has_many`. 

I should also note that the `message` object I got comes back from a callback in the `SaveOperation` so I don't have access to the original query that created it.

```crystal
class SaveMessage < Message::SaveOperation

  after_save do |message|
      # I want to ship this data off somewhere
      # but can't because of the preload error
     MessageSerializer.new(message)
  end
end
```

**Comment by matthewmcgarvey** [comment]
I've been referencing Elixir's Ecto library a bit lately and they have a way to add associations to an object after it has been loaded. You call `Repo.preload message, :user` to add the user association to the message object. I think we should be able to do something like that with our query objects.

I support the explicit-ness of Avram and I think the user method you added to Message would hide the database operation that is happening.

https://hexdocs.pm/ecto/Ecto.Repo.html#c:preload/3

**Comment by jwoertink** [comment]
I actually totally forgot that I can skip the preload with `message.user!`, but we should definitely make this a lot easier to deal with. No error message pointed me in that direction, and I only remembered it was a thing about an hour ago 😅
