### ISSUE TITLE
`avram_enum` should map to a `String` type in database

### ISSUE THREAD

**Issue by akadusei** [luckyframework/avram#567]
Currently, `avram_enum` saves the enum value (an `Int32`) to the database. This may not be ideal for two reasons:

1. Enum values (if not set explicitly) are order-dependent; the values change when the member ordering changes.
1. You could not make sense of the integers if you peeked directly into the database.

For instance, giving the following enum:

```crystal
avram_enum Status do
  Active # 0
  Inactive # 1
end
```
If you decided later to add another member:

```crystal
avram_enum Status do
  Active # 0
  Waiting # 1 <= New member
  Inactive # 2
end
```

Now your values have changed. If you do not remember to do a migration of sort, you're in for a lot of trouble; your current values in the database may map to different members on this enum. In this particular example, all `Status::Inactive` enums (saved as `1`) in the database would map to `Status::Waiting` after this change.

To resolve this, I propose enums be saved as `String` instead. We could make use of [`Enum.parse`](https://crystal-lang.org/api/0.35.1/Enum.html#parse(string:String):self-class-method) to parse the string representation retrieved from the database to its actual enum member.

After that you could *toss and turn* your enum members, and everything would be fine (as long as you to not change their names).

I have working code here: https://github.com/GrottoPress/shield/blob/095b63e3727f59ada34a9387168cf4b45bbb2613/src/charms.cr#L673

There may be scenarios that make the current implementation worth it that I've not thought about (seeing that I'm being biased here). So I would love to hear what everyone else thinks about this.

**Comment by robacarp** [comment]
There are certainly benefits to this. When you're looking at the database with an Int enum column, you have no context for what the random int means. 

However, when you have strings it's not possible to setup a ranked relationship between enum values (eg. you can't query `select * from users where role >= moderator`).

**Comment by akadusei** [comment]
> However, when you have strings it's not possible to setup a ranked relationship between enum values (eg. you can't query select * from users where role >= moderator).

Fair point. I guess one can select all users from the database and filter out the moderators after that. I'm thinking:

```crystal
UserQuery.new.select &.role.>=(User::Role.new :moderator)
```
I'm not too sure about this, though.

**Comment by akadusei** [comment]
Closing this in light of #639
