### ISSUE TITLE
Has_many association too greedy

### ISSUE THREAD

**Issue by rmarronnier** [luckyframework/avram#571]
I really don't want to spam Lucky repos issues but after migrating to 0.25 I got some some errors (https://github.com/luckyframework/website/issues/541) which I thought were fixed. 

Now I have some weird behaviors which are best explained by this custom Avram spec which fails :

```crystal
    it "joins the two associations correctly" do
      tag = TagBox.create
      post = PostBox.create
      post2 = PostBox.create
      TagBox.create
      TaggingBox.new.tag_id(tag.id).post_id(post.id).create

      post2.tags.size.should eq 0
    end
```

which is a variation of the original :

```crystal
    it "joins the two associations" do
      tag = TagBox.create
      post = PostBox.create
      TagBox.create
      TaggingBox.new.tag_id(tag.id).post_id(post.id).create

      post.tags.should eq [tag]
    end
 ```
 
 post2.tags lists **_all_** tags regardless if a `Tagging` binds them with `post2`.
 
 In my application, `current_user.groups` returns all groups available in the database, which is very concerning security wise. It was working as expected before 0.25.
 
 If this issue is moot because of my misunderstanding (most probable), what is the best way to get all the tags of a post ? Is post.tags a code smell ? Should I use a PostQuery instead ? In other words, what does `post.tags` really do ? post is a Post instance and not a PostQuery, right ? So what does it gets translated into ?

**Comment by jwoertink** [comment]
Sounds like a bug to me. I think if you have `current_user.groups`, that should give you groups that only belong to that user.  Do you happen to see the SQL being generated from that call? I don't think you can call `to_sql` on the association since it's not a query object, so you might have to just turn logging all the way up. `DB::Log.level = :debug` I think 🤔

**Comment by rmarronnier** [comment]
From my app (you can replace in your head "fridge" with "group") :
`fridges = FridgeQuery.new.where_users(UserQuery.new.id(current_user.id))` is translated to `["SELECT fridges.id, fridges.created_at, fridges.updated_at, fridges.name FROM fridges INNER JOIN pairings ON fridges.id = pairings.fridge_id INNER JOIN users ON pairings.user_id = users.id WHERE users.id = $1", "25c34ecc-26d5-4995-a89b-3a255667bac4"]`
and gives correct results (ie only fridges which are associated with the current user)
Which means only the `user.fridges` shortcut fails.

**Comment by jwoertink** [comment]
Ok. Thanks for reporting! I'll dig in and try to get a patch released. Might be a little slow because of the holiday.

**Comment by rmarronnier** [comment]
No problem, thanks for the pointers. Happy holidays !

**Comment by jwoertink** [comment]
@rmarronnier Avram 0.18.1 has been released which fixes this. Just do a `shards update` and you should be good!

**Comment by rmarronnier** [comment]
@jwoertink Thanks so much for this ! Happy christmas ;-)
