### ISSUE TITLE
Tables with no primary key

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#6]
With some schemas there might be join tables that don't need a primary key.

```
user_roles
  user_id : integer
  role_id : integer
```

With a setup like this, LuckyRecord currently doesn't like this table. It would be cool to be able to specify a model like this for doing joins through this table when you'd never need to query on this table directly.

**Comment by lesderid** [comment]
Is there a solution for this yet? This is a pretty major issue for anything more than the simplest database schemas.

**Comment by paulcsmith** [comment]
Right now there is not. Can you explain what your use case is? This should not be an issue for any new app as a primary key is added for all tables. Are you using an existing Schema with Avram that does not have primary keys? I’ve personally never worked on a database where tables don’t have a primary key so I’m trying to understand the use case so I can prioritize this

**Comment by lesderid** [comment]
Having no primary key at all is usually not very useful, but it can make sense to have a composite primary key (i.e. a primary key over more than one column).

An example would be the 'tag map' table of a toxi-style tagging system (see http://howto.philippkeller.com/2005/06/19/Tagsystems-performance-tests/). In many cases having a composite key over the two (foreign key) IDs is sufficient, and a separate ID serving as a primary key doesn't serve much of a purpose.

**Comment by paulcsmith** [comment]
@lesderid that makes sense. Thanks for sharing. In the meantime can you still use Avram and add the primary key, or is this currently a show stopper for you?

**Comment by lesderid** [comment]
Adding the primary key is fine for now. 

(FWIW, Laravel devs ignored this issue, which annoyed a lot of people: https://github.com/laravel/framework/issues/5355#issuecomment-72261848.)

**Comment by jwoertink** [comment]
closing in favor of 96

**Comment by jwoertink** [comment]
This is actually not done. You still always have to call `primary_key`. https://github.com/luckyframework/avram/pull/121 added in the ability to use `skip_default_columns` which remove the `primary_key` and `timestamps`; however, if you don't manually call `primary_key` you'll get this error:

```
in lib/avram/src/avram/model.cr:100: undefined constant PRIMARY_KEY_TYPE

        primary_key_type: {{ PRIMARY_KEY_TYPE }},
                             ^~~~~~~~~~~~~~~~
```

Because the `primary_key` macro sets up those constants.

**Comment by jwoertink** [comment]
After some thought, I've decided that tables should always specify a primary key. I know that I have apps with tables that don't have primary keys, but they would only be existing apps coming to Lucky, and not new ones being started from scratch. In those cases, it's not difficult to create a primary key on the table, and fill it with data even if you never plan on using that. In this instance, it's more of a tradeoff between allowing for an edge-case vs potentially losing some type-safety. 

We will need to document how to handle this edge case, so I will add an issue to the website for some documentation. Also, we are planning on adding in support for views which also don't normally have primary keys, but they will be handled differently than tables.

**Comment by jwoertink** [comment]
Oh, and just for clarity, I'm not tossing out the idea of composite primary keys. I haven't put any thought in to those yet, but this is just the idea of not allowing for "no primary key". https://github.com/luckyframework/avram/issues/129
