### ISSUE TITLE
Make the trip to the database always in save operations

### ISSUE THREAD

**Issue by akadusei** [luckyframework/avram#604]
Currently, *Avram* does not make the trip to the database if no columns changed. I assume this is for performance?

While working on #596, I encountered a situation where some of the nested save operations are never rolled back. As @matthewmcgarvey rightly pointed out, "... the whole thing is wrapped in a transaction so exiting the transaction undoes the changes, right?"

This is true, except for when the parent operation has no columns changed. In that particular instance, any updated nested record remains intact. When no columns changed, nested operations run, outside of any transaction, here:

https://github.com/luckyframework/avram/blob/84e431c6dfde0078e29dc0ad8f603a2082b8c917/src/avram/save_operation.cr#L316-L320

The essence of #600 is to revert any nested saves that could not be rolled back automatically. From my tests done locally, it works.

However, I believe we are trying to solve a problem that should not exist at all. Just let the save happen whether or not columns change. I'm talking about changing `#save` to something like this:

```crystal
  def save : Bool
    before_save

    if valid?
      transaction_committed = database.transaction do
        insert_or_update
        saved_record = record.not_nil!
        after_save(saved_record)
        true
      end

      if transaction_committed
        saved_record = record.not_nil!
        after_commit(saved_record)
        self.save_status = SaveStatus::Saved
        Avram::Events::SaveSuccessEvent.publish(
          operation_class: self.class.name,
          attributes: generic_attributes
        )
        true
      else
        mark_as_failed
        false
      end
    else
      mark_as_failed
      false
    end
  end
```

This would solve a lot of problems, including:

- `updated_at` column would always be updated. If I called `SavePost.update`, I would expect `updated_at` to be updated, even if no other column changed. Currently, it doesn't.
- `after_save` would always be guaranteed to run for valid operations.
- We might not need `#revert` (#600). At least, nested `.has_one` operations would work without it.
- We would not need `after_completed`

The current implementation creates API inconsistencies between creates and updates, and introduces unnecessary cognitive overhead for updates:

- `after_save` always runs for create operations. It is not guaranteed to run in update operations.
- `after_commit` always runs for create operations if transaction committed successfully. This renders `after_completed` redundant in create operations.
- In update operations, where you need the nested operations to run even if no column changed on the parent, `after_completed` seems like a good fit. Except you may want to roll back if a nested operation fails -- roll backs happen only in `after_save`. In such situations, you may call your nested operations in `after_save` and account for when `after_save` may not run in `after_completed`:

  ```crystal
  after_save my_nested_operation

  after_completed do |saved_record|
    my_nested_operation(saved_record) if changes.empty?
  end
  ```

From an API consumers perspective, there is too much internal implementation details I have to worry about, especially regarding updates.

Remove the need to avoid the database trip, and all these issues go away.

There's still a lot I do not know about *Avram*, so maybe my proposal has issues I have not thought about? I would be happy to know.

**Comment by matthewmcgarvey** [comment]
There's some points that I think I agree with and some that I don't:

Agree:
- I agree that we could use the transaction to avoid implementing the `#revert` code (this is definitely my favorite part of this issue 😄 )
- I agree that we could remove the `after_completed` if `after_save` and `after_commit` worked even if nothing changed in the database

Disagree:

- I don't agree with sending changes to the database if nothing was changed
- I don't agree with updating the `updated_at` timestamp if nothing was changed

In rails, if I load a record from the database and immediately call save on it, it doesn't actually write to the database and the updated_at column does not change. I think we could move the check for updated attributes into the database transaction and get the same benefits without the downside of making unnecessary database calls.

**Comment by akadusei** [comment]
> In rails, if I load a record from the database and immediately call save on it, it doesn't actually write to the database and the updated_at column does not change.

Now that I think about it, I may have to agree with you.

> I think we could move the check for updated attributes into the database transaction and get the same benefits without the downside of making unnecessary database calls.

This is brilliant! Just to clarify, you mean something like this?:

```crystal
  def save : Bool
    #...
    if valid?
      transaction_committed = database.transaction do
        insert_or_update unless changes.empty? && persisted? # <=== 
        saved_record = record.not_nil!
        after_save(saved_record)
        true
      end
  #...
  end
```

**Comment by matthewmcgarvey** [comment]
@akadusei as I said in the commit, it should be:
```crystal
insert_or_update unless changes.empty? || persisted? # no changes or already saved
```
