### ISSUE TITLE
Not all DB tasks have a "quiet" option 

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#620]
Some of the tasks like [db.create](https://github.com/luckyframework/avram/blob/master/src/avram/tasks/db/create.cr#L5) have an option to [silence them](https://github.com/luckyframework/lucky_cli/blob/master/src/web_app_skeleton/spec/setup/setup_database.cr#L1-L2). This is used in specs so when you run `crystal spec` you don't see the migration running every time. The `db.create` and `db.migrate` tasks have this option, but [db.reset](https://github.com/luckyframework/avram/blob/master/src/avram/tasks/db/reset.cr) and [db.drop](https://github.com/luckyframework/avram/blob/master/src/avram/tasks/db/drop.cr) do not.

**Comment by nodeMD** [comment]
Hello 😃 
I've added a PR to address that issue: https://github.com/luckyframework/avram/pull/675
Please take a look and review when you will have a moment
