### ISSUE TITLE
`.table_for` does not return table name

### ISSUE THREAD

**Issue by akadusei** [luckyframework/avram#638]
https://github.com/luckyframework/avram/blob/e983b9c19a9746610ed7d1ce53ce9311f117c6b2/src/avram/table_for.cr#L1-L8

The `.table_for` macro infers the table name, rather than return the name set by the `.table` macro. This means one cannot use the `.table_for` macro if the table name does not match the underscored class name.

The `.table` macro already infers the table name if not explicitly given, so I suggest the `.table_for` macro be refactored thus:

```crystal
module Avram::TableFor
  macro table_for(model)
    {{ model.resolve.constant(:TABLE_NAME) }}
  end
end
```

**Comment by akadusei** [comment]
If this change happens, then `.add_belongs_to` macros can use the `.table_for` macro instead of a `references` argument. This means, this macro:

https://github.com/luckyframework/avram/blob/fa1ba00ca172dd766b03203e39629536e8411c74/src/avram/migrator/create_table_statement.cr#L121

...can be simplified thus:

```crystal
# NOTE: The `references` argument has been removed
macro add_belongs_to(type_declaration, on_delete, foreign_key_type = Int64, unique = false)
      # ... <truncated for brevity>

      {% if optional %}
        {% type = type_declaration.type.types.first %}
      {% else %}
        {% type = type_declaration.type %}
      {% end %}

      {% foreign_key_name = type_declaration.var + "_id" %}
      %table_name = table_for({{ type }})

      # ... <truncated for brevity>
    end
  end

**Comment by matthewmcgarvey** [comment]
Personally, I would rather remove the `table_for` macro. It provides little benefit as you've pointed out and only "appears" to connect to the model while it really doesn't.

I would not be in favor of making this change since it would require the model to exist before creating the table. I don't think that is a workflow that everyone (i doubt even the majority) follows and would cause issues.

**Comment by akadusei** [comment]
> I would not be in favor of making this change since it would require the model to exist before creating the table.

Everything else (queries, operations, etc) requires the model to exist first, though. Models must be `require`d earlier, otherwise your app won't compile at all. There are other macros used in migrations that assumes models already exist.

**Comment by akadusei** [comment]
Closing this in light of #660
