### ISSUE TITLE
New method to query for value inside of array column

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#640]
If you have an array column, you may want to search for records that have a specific value inside of that array. Right now we have to use a raw `where` to do this.

```crystal
# currently
UserQuery.new.where("? = ANY (users.tags)", "lucky")

# proposed
UserQuery.new.tags.contains("lucky")
# or maybe
UserQuery.new.tags.includes("lucky")
```

This method should raise a compile-time error when called against any column that's not an array.

**EDIT:** I should also note that depending on the array generic type, you should only be allowed to pass that type in...

```crystal
# assumes column friends : Array(UUID)
UserQuery.new.friends.contains(UUID.random) # this is ok

UserQuery.new.friends.contains(9) # this should fail
```

We could possibly make an exception for `Array(String)`, though, that might be too magical

**Comment by matthewmcgarvey** [comment]
I think we could have the value follow all the normal parsing rules. Int primary keys can still do `.find("1")` and all that.
