### ISSUE TITLE
Add a CASCADE option to TRUNCATE

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#648]
https://github.com/luckyframework/avram/blob/5e29f75371dca5a2bc16858163dc3790cabfbfcb/src/avram/queryable.cr#L36-L39

It would be cool to have an overload that allows us to pass an optional `cascade` option to `truncate`. Right now, if you have a table with a foreign key constraint, and you try to truncate it, you'll get a [postgres error](https://stackoverflow.com/questions/56700466/postgresql-truncate-table-with-foreign-key-constraint/56700574) mentioning 

> cannot truncate a table referenced in a foreign key constraint

To get around this, you have 2 options.

1. call `TRUNCATE TABLE the_table, other_table, one_more_related`
2. call `TRUNCATE TABLE the_table CASCADE` which will handle the first for you.

The second option could be doable just by adding a flag.

For a work around, just call `MyQuery.new.delete` which will just delete all of the records. 

Note: We are already including the `CASCADE` when truncating the whole db https://github.com/luckyframework/avram/blob/master/src/avram/database.cr#L202... I'm not sure the impact, but maybe we can just always CASCADE?

**Comment by jaitaiwan** [comment]
I did some research and I can confirm that truncate always supports cascade so it's an easy include here. Just have to determine if there's a particular name for the flag we want.
