### ISSUE TITLE
Delete operations don't have AvramAttributes?

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#649]
I know I can work on fields of `record` in delete operations, but I can't insert errors on fields or run validators and have the delete fail based on their results because delete operations don't seem to have AvramAttributes. So far, I just raise an exception to stop the delete.

**Comment by jwoertink** [comment]
They do. Take a look at these specs: https://github.com/luckyframework/avram/blob/master/spec/operations/delete_operation_spec.cr and https://github.com/luckyframework/avram/blob/master/spec/operations/define_attribute_spec.cr#L38-L50 and https://github.com/luckyframework/avram/blob/master/spec/operations/operation_needs_spec.cr#L37-L42

You have access to all of the model's columns, `attribute`, `needs`, `file_attribute`, and you can use both `add_error` and `attribute.add_error`.

**Comment by BrucePerens** [comment]
Yes, but the attributes aren't autogenerated from the model like a SaveOperation. In your spec, you fill them in explicitly.

**Comment by jwoertink** [comment]
I'm pretty sure they are. If you look at [this spec](https://github.com/luckyframework/avram/blob/master/spec/operations/delete_operation_spec.cr#L20-L21) you'll see it calls `record.title` then on the next line it only references `title` allowing us to set an error on that attribute specifically. Is that what you mean?

Do you have any code we can see to reproduce the issue? Or could you help clarify what isn't working exactly?

**Comment by BrucePerens** [comment]
This is my entire operation. Below I can access `record.type`, but not `type.value`.
```crystal
class DeleteTopic < DeleteHierarchical(Topic)
  include DeleteReplies
  before_delete :do_before_delete

  def do_before_delete
    STDERR.puts type.value # The compiler blows up on this line because type.value doesn't exist.
    if record.type == "general" || record.type == "reviews"
      raise RuntimeError.new(%Q[Deletion of the "General Discussion" and "Reviews" topics is not allowed.])
    end
    delete_dependent(record.posts!)
  end
end

**Comment by BrucePerens** [comment]
OK, I think I understand the problem. The root class for this is Avram::DeleteOperation(T). It needs to be something from the model, right?
