### ISSUE TITLE
Wrong query being generated from non-chained methods

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#650]
I'm trying to upgrade one of my apps using Avram 0.17.0 to 0.19.1 (with all the lucky and crystal updates). There's 1 query in my app in particular that ran fairly quick, but after the update, it basically halts my app.

Here's the raw (but redacted) SQL:

```
SELECT members.id, members.status, members.field_one, members.field_two, members.field_three, members.LotsMoreColumns FROM members WHERE members.field_one = $1 AND members.field_two = $2 AND members.field_three = $3 ORDER BY CASE status WHEN 0 THEN 4 WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 3 END ASC LIMIT 1;
```

Here are my current findings:

Using this postgres version running locally on my machine. (no docker, etc...)

```
PostgreSQL 12.6 on x86_64-apple-darwin19.6.0, compiled by Apple clang version 12.0.0 (clang-1200.0.32.29), 64-bit
```

First I noticed that the action hitting this query in Lucky had a huge difference. Using Pulsar, I saw this:

```
# Avram 0.17.0
Duration 00:00:00.079214705
```

```
# Avram 0.19.1
Duration 00:00:13.994559101
```

Running directly in PSQL with the `\timing` option runs this query in `0.476 ms`

Next I decided writing a simple test using crystal-db and pg directly. I made sure to set up each file using the exact same versions of crystal-db and pg as each version of the Lucky apps.

Here is the sample test:

```crystal
require "db"
require "pg"

SQL = <<-SQL
the sql from above
SQL

DB.open("postgres://postgres@localhost:5432/bar") do |db|
  elapsed_time = Time.measure do
    db.query(SQL) do |rs|
      puts "#{rs.inspect}"
    end
  end

  pp elapsed_time
end
```

```
# crystal 0.35.1
# crystal-db 0.9.0
# pg 0.21.1
00:00:00.005255137
```

```
# crystal 0.36.1
# crystal-db 0.10.0
# pg 0.23.1
00:00:00.005240836
```

As you can see, they're pretty much the same. Next test is to use a single file Avram to run that one query.
I tried to keep this as close to what's actually being used in the app, so there's a few "hacks".

```crystal
require "db"
require "pg"
require "avram"

class BarDatabase < Avram::Database
end

BarDatabase.configure do |settings|
  settings.credentials = Avram::Credentials.parse("postgres://postgres@localhost:5432/bar")
end

Avram.configure do |settings|
  settings.database_to_migrate = BarDatabase
end

alias BarID = String

module Avram::Migrator::Columns::PrimaryKeys
  class BarIDPrimaryKey < Avram::Migrator::Columns::PrimaryKeys::Base
    def initialize(@name)
    end

    def column_type : String
      "character varying(18)"
    end
  end
end

module Avram::Migrator::Columns
  class BarIDColumn < Avram::Migrator::Columns::Base
    @default : String? = nil

    def initialize(@name, @nilable, @default)
    end

    def column_type : String
      "character varying(18)"
    end
  end
end

abstract class BaseModel < Avram::Model
  skip_default_columns

  def self.database
    BarDatabase
  end
end

class Member < BaseModel
  STATUS_ORDER = "CASE status WHEN 0 THEN 4 WHEN 1 THEN 1 WHEN 2 THEN 2 WHEN 3 THEN 3 END"
  table :members do
    primary_key id : BarID
    column status : Int16
    column field_one : String
    column field_two : String
    column field_three : String
    # lots more columns
  end
end

class MemberQuery < Member::BaseQuery
  def for_key(key_one : String, key_two : String)
    field_one(key_one.downcase)
    field_two(key_two.downcase)
    order_by(Member::STATUS_ORDER, :asc)
  end
end

pp MemberQuery.new.for_key("key_one", "key_two").field_three("key_three").first?
```

```
# crystal 0.35.1
# Avram 0.17.0
2021-03-17T16:44:46.626797Z   INFO - avram.query:  -- local: {"model" => "Member", "query" => "...", "args" => "[...]",  "duration" => "126.5ms"}
#<Member:0x10793de40 ...>
# Took 6s to compile and run
```

```
# crystal 0.36.1
# Avram 0.19.1
#<Member:0x1120a2e40 ...>
2021-03-17T16:42:55.570948Z   INFO - avram.query:  -- local: {"model" => "Member", "query" => "...", "args" => "[...]", "duration" => "4.45s"}
# Took 11s to compile and run
```

(the reversed output is intentional since that's how it outputs in each version)

So the older one runs in 126ms, but the newer one runs in 4.45s... that's a MASSIVE increase... In both cases, I just ran `crystal avram.cr`. No release builds or any sort of extra optimization on them.

**Comment by jwoertink** [comment]
Ok, it didn't take a whole lot of sleuthing... It was this PR https://github.com/luckyframework/avram/pull/411

I took the old code which was using the commit right before this PR was merged ([release 0.17.0](https://github.com/luckyframework/avram/commits/b002ead126de2e4e47c1ca9c2192ad86db91f844)), then I updated to use `commit: "b002ead126de2e4e47c1ca9c2192ad86db91f844"` which was the commit that PR was merged in. 

```
# crystal 0.35.1
# Avram commit b002ead126de2e4e47c1ca9c2192ad86db91f844
2021-03-17T18:02:15.365402Z   INFO - avram.query:  -- local: {"model" => "Member", "query" => "...", "args" => "[...]",  "duration" => "4.9s"}
#<Member:0x105aebe40 ...>
# Took 12s to compile and run
```

At this point, it might be too far in to revert, so we need to figure out how we can keep the same functionality, and fix the performance issue. Any help would be much appreciated!


/cc. @paulcsmith @bnjamin

**Comment by jwoertink** [comment]
WOW..... ok... I figured it out by pure dumb luck. Turns out this isn't really that big of an issue as I originally thought, however, I think we need to come up with a way to prevent this level of anxiety attack 😂 

If you're following along, and didn't notice what the issue was, I'll give you a hint: "look at the custom query method"....

See, when #411 was merged in, it made it so queries are no longer mutated. I missed updating that method.

```crystal
# before change
def for_key(key_one : String, key_two : String)
  field_one(key_one.downcase)
  field_two(key_two.downcase)
  order_by(Member::STATUS_ORDER, :asc)
end

# after change
def for_key(key_one : String, key_two : String)
  field_one(key_one.downcase).field_two(key_two.downcase).order_by(Member::STATUS_ORDER, :asc)
end
```

The result after making that change: `"duration" => "14.21ms"` 😂 

I'm not 100% sure, but in the first one, I think it's making 3 separate query objects, but it still seemed to give me the correct SQL output. So both of these are giving me the same SQL, but second one builds it on to the same object? 

Now this issue becomes, how do we detect that first one? Can we even detect that to say "This is bad"? Or is this just one of those things where as time goes on, people won't have code like this?

**Comment by russ** [comment]
I would venture to say this is a way out edge case. If there is an easy way to bubble up an error then sure, otherwise I think as long as docs are updated, it’s a non issue.

**Comment by robacarp** [comment]
This is the kind of thing a linter would be responsible for catching. If someone does `field_one(...) ; field_two(...)` the first will have no effect. I don't think you can catch that without static analysis, and even then it might be difficult due to the dynamic method names.

**Comment by matthewmcgarvey** [comment]
To be clear, the unchained implementation that to ~4 seconds was because the query didn't have the `field_one` and `field_two` conditions right?

**Comment by jwoertink** [comment]
The unchained query still had both `field_one` and `field_two` in it. I feel like it shouldn't have, but it was still generating the correct query.

**Comment by matthewmcgarvey** [comment]
That's definitely a serious bug. That means that there's problems with re-using queries.

**Comment by jwoertink** [comment]
I'll try to write up a spec that recreates it just to confirm so we at least have something to work off

**Comment by jwoertink** [comment]
Fun times... I can't recreate it inside of Avram... 😕  I must have missed something along the way. I'm trying different combinations, but I can't get the Avram spec to fail the same way. It may be something specific that we had in our code... I think @russ might be right; this is probably a non-issue at this point. I'm gonna close this out, but if I can find a way to re-create it, I'll open it back up.
