### ISSUE TITLE
Move Nothing to a top level Avram namespace

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#673]
Getting an error that looks like this is a bit jarring, especially to newcomers:

```
| Error: no overload matches 'SaveFortune.new' with types Fortune, Lucky::Params, id: Avram::NeedyInitializerAndSaveMethods::Nothing, created_at: Avram::NeedyInitializerAndSaveMethods::Nothing, updated_at: Avram::NeedyInitializerAndSaveMethods::Nothing, text: Avram::NeedyInitializerAndSaveMethods::Nothing, user_id: Avram::NeedyInitializerAndSaveMethods::Nothing
web          |
```

At least if it just says `Avram::Nothing`, it'll be a bit easier to parse

**Comment by robacarp** [comment]
What's the benefit of Nothing instead of just a nilable there?

**Comment by matthewmcgarvey** [comment]
Link to where `Nothing` is defined: https://github.com/luckyframework/avram/blob/5b9be2190062550728c9dff78c3012042ec07a6f/src/avram/needy_initializer_and_save_methods.cr#L190-L191

In avram's case, `Nothing` is used to signify that nothing was passed in. `nil` is still something if it was passed intentionally. Without `Nothing` it would be difficult/impossible to clear a value (go from string to nil).
