### ISSUE TITLE
Changing how COUNT() works in queries

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#686]
Today I learned that you can take a query, and wrap it with an outer select count, and 1. it's about the same speed, 2. it allows you to ignore all those weird group by column aggregate errors you get with postgres.

In my case, I have this query that does a `SELECT DISTINCT ON (col) col` which you can't do a count on (with how things work now). You can do `SELECT COUNT(DISTINCT col)`, but it seems this is actually slower. 

Here's an example:

```sql
SELECT COUNT(*) FROM (SELECT DISTINCT ON (users.username) users.id, users.created_at, users.updated_at, users.username FROM users WHERE users.soft_deleted_at IS NULL) AS count;
```

If we changed how the current `select_count` method works, to do this, then it opens up to being about to count on just about any query you run.

Here's some stats on a table I use in production with 5+ million records:

```
production_db=> select count(*) from users;
  count
---------
 5028502
(1 row)

Time: 403.789 ms
production_db=> select count(*) from (select * from users) as count;
  count
---------
 5028502
(1 row)

Time: 403.690 ms
```

I'm proposing we change https://github.com/luckyframework/avram/blob/6c121361311bd190243d0bd663b0976674a6263d/src/avram/query_builder.cr#L193-L195 to just be something more like

```crystal
def select_count
  "SELECT COUNT(*) FROM (#{to_prepared_sql}) AS count"
end
```

Can anyone things of an edge case where this might return the wrong value, or where this would end up being a ton slower?

**Comment by wyhaines** [comment]
Getting _accurate_ counts from PG is unavoidably slow. There is a technique that can be used to get very fast approximate counts, but if the goal here is to simply get an accurate count for any arbitrary SQL, then what you propose is a workable general pattern.

You should run some explain analyze comparisons on some queries to be sure that the query planner in PG is doing what you think that it is doing, but your pattern above really just says, "query a bunch of stuff, and then count the rows that you just queried", and that should always work.

I would think, though, that for counts, you'd be better off keeping the field count as low as possible. Query only the primary key, or only the field that you are selecting distinct on, since all that you need is to get a single field back for each row that matches your query in order to get a count.

```sql
select count(*) from (select id from users) as count;
```

```sql
SELECT COUNT(*) FROM (SELECT DISTINCT ON (users.username) users.username FROM users WHERE users.soft_deleted_at IS NULL) AS count;
```

**Comment by wyhaines** [comment]
I have done a little testing with explain analyze, just to confirm my suspicion, and in general, you end up with exactly the same query plan using the `select count(*) from (select ... ) as count;` approach as the `select count(*) from ...` approach.

**Comment by matthewmcgarvey** [comment]
I would feel better about doing something like this if we could find examples of other ORMs discussing/adopting it

**Comment by jwoertink** [comment]
I didn't really look to see how other ORMs handle this. I didn't really want to do what Rails does though because Rails will change how count works based on the query you're doing since it may return a number, or a hash. For us, the `select_count` should always return `Int64`.

I think a lot of other frameworks just expect you to drop down to raw SQL when things get a bit more complex. So far I haven't found a downside to going this path. I'll keep looking around though to see if I can find another ORM doing this.

Here's the StackOverflow I came across https://stackoverflow.com/questions/11250253/postgresql-countdistinct-very-slow

**Comment by wyhaines** [comment]
The only downside is that if you keep the _full_ query, you may end up doing more IO in your database than you want to do. Basically, you should only query the minimum amount of data necessary to satisfy the requirements of the query's row selection logic.

So, don't `select *` when you can `select id`, basically. You can get approximate counts extremely quickly with postgresql, even for arbitrarily complex queries, and you can write a simple trigger/stored procedure pair that will let you maintain exact full-table counts, but there is no _fast_ way to get exact counts for anything that isn't a full-table count, including those distinct counts. 

And speaking of the distinct counts, here are a couple explain plans for a couple functionally identical count queries. The two queries:

```sql
select count(distinct server_id) from telemetries;
```

```sql
select count(*) from (select distinct on (server_id) server_id from telemetries) as count;
```

They both return the same thing:

```
 count 
-------
    13
(1 row)
```

However, there is a very interesting difference in the explain plan that is produced for the two queries, and the performance of the two queries. First, the plan for the simpler, more direct count query:

```sql
                                                            QUERY PLAN                                                            
----------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=349708.21..349708.22 rows=1 width=8) (actual time=14298.787..14298.789 rows=1 loops=1)
   ->  Seq Scan on telemetries  (cost=0.00..338070.97 rows=4654897 width=16) (actual time=27.138..11093.802 rows=4600463 loops=1)
 Planning Time: 0.099 ms
 JIT:
   Functions: 4
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 1.918 ms, Inlining 0.000 ms, Optimization 5.136 ms, Emission 20.923 ms, Total 27.977 ms
 Execution Time: 14300.819 ms
(8 rows)

```

14.3 seconds.  Now, consider the other syntax, which is what you are proposing:

```sql
                                                                                      QUERY PLAN                                                                                      
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Aggregate  (cost=364483.83..364483.84 rows=1 width=8) (actual time=1312.319..1312.321 rows=1 loops=1)
   ->  Unique  (cost=0.56..364483.68 rows=12 width=16) (actual time=3.284..1312.271 rows=13 loops=1)
         ->  Index Only Scan using telemetries_server_id_data_key_idx on telemetries  (cost=0.56..352846.44 rows=4654897 width=16) (actual time=3.280..1066.152 rows=4600463 loops=1)
               Heap Fetches: 528435
 Planning Time: 0.090 ms
 JIT:
   Functions: 4
   Options: Inlining false, Optimization false, Expressions true, Deforming true
   Timing: Generation 0.530 ms, Inlining 0.000 ms, Optimization 0.173 ms, Emission 2.824 ms, Total 3.527 ms
 Execution Time: 1312.946 ms
(10 rows)

```

The first one uses a sequential scan, while the second form uses an existing index to reduce the search space, returning the count in less than one tenth of the time of the simple count.

I can not find any issue with performing counts the way that you are proposing, and I think that this approach is actually a better overall choice.

**Comment by jwoertink** [comment]
Wow! That's awesome seeing the stats side by side like that. Thanks for the info @wyhaines. I'm working on a PR now. I'll be sure to add a few specs around different queries to ensure we're getting the numbers we would expect.
