### ISSUE TITLE
Simple cleanups and refactors

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#696]
There's a few places in the code that could use some refactors and cleanups. I'm just documenting them here so I can get to them later.

This can use the `join {}` block form which is slightly faster 
https://github.com/luckyframework/avram/blob/d43f0361ab3c937b8485cf490802482d3005a8f1/src/avram/query_builder.cr#L244-L245 

Same here. Use the join with block form which is slightly faster
https://github.com/luckyframework/avram/blob/d43f0361ab3c937b8485cf490802482d3005a8f1/src/avram/insert.cr#L16-L17

These don't need to be in strings. We can just call `.id` right on the type
https://github.com/luckyframework/avram/blob/d43f0361ab3c937b8485cf490802482d3005a8f1/src/avram/model.cr#L219
https://github.com/luckyframework/avram/blob/d43f0361ab3c937b8485cf490802482d3005a8f1/src/avram/model.cr#L222

**Comment by matthewmcgarvey** [comment]
And we can update the supported crystal version in `shard.yml` to be `>= 1.0.0`
