### ISSUE TITLE
The model reference in add_belongs_to can lead to issues

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#709]
Ref: https://github.com/luckyframework/avram/pull/685#issuecomment-858698957

Right now, the type used in `add_belongs_to` is only used for generating a table reference name, and not for enforcing a type. If you use a model that's in a namespace, you won't get the reference that you're expecting in some cases.

Take this for example:

```crystal
module MyApp
  class Post < BaseModel
    table :posts do
    end
  end
end

# then in your migration
def migrate
  create table_for(MyApp::Post) do
    # ...
    add_belongs_to user : MyApp::User, on_delete: :cascade
  end
end
```

This will create the `user_id` column, but tell postgres that the foreign key references the `my_app_users` table. To fix this, you would add the `references` option:

`add_belongs_to user : MyApp::User, references: :users, on_delete: :cascade` or don't use a namespaced type here.
`add_belongs_to user : User, on_delete: :cascade`.

We can either make this easier to know (no clue how), or we can look at trying to resolve the model to get its table name... 

This might be a tricky one.

**Comment by jwoertink** [comment]
Just tossing out ideas here, but what if we just make it an error that if you pass in a namespace, it blows up without the `reference` option? Even if your table is namespaced like `my_app_users`, then you can still be explicit in that reference.

```crystal
add_belongs_to user : MyApp::User, references: :my_app_users, on_delete: :cascade
```

**Comment by robacarp** [comment]
> what if we just make it an error that if you pass in a namespace, it blows up without the reference option?

That might not be a perfect solution, but I think it would be an improvement to the current behavior. It's bitten me a couple times and I had to stumble through getting it to work.
