### ISSUE TITLE
Operations fail when passing in the value of an enum as a String

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#713]
https://github.com/luckyframework/avram/blob/e638ffb8eb5e8088449dfa63cb61a0739212f38d/src/avram/charms/enum_extensions.cr#L12-L13

If you have something like this in your html:

```crystal
needs kind : Some::Enum
hidden_input(operation.kind, value: kind.value)
```

`kind.value` returns `Int32` which is allowed in the tags, and converted to String. The param passed over is `"1"` instead of `1` which causes it to do `Some::Enum.parse?("1")`. That ends up returning `nil`, and your operation fails saying `kind is required`.... Then you spend time debugging params and see that it's being passed over and have no clue what's going on.

We need to either allow the enum values to be passed over as strings (as well as the member name), or we raise an error to say that it's invalid.

Right now, the fix for this is to change your html to this:

```crystal
hidden_input(operation.kind, value: kind.to_s)
```

@matthewmcgarvey what are your thoughts on it?

**Comment by matthewmcgarvey** [comment]
I guess we could add a check to see if the value is an integer before passing it to `parse?`. That make sense or am I missing something?

**Comment by jwoertink** [comment]
That's what I was thinking too. We'd just have to make sure that if you have a type `String`, and say you're passing in a zip code of `90210`, we don't send that to Int by mistake.

**Comment by matthewmcgarvey** [comment]
Just checked in crystal playground but it's not possible to have an enum be all numbers so we should be fine
