### ISSUE TITLE
Remove crystal side UUID generation

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#714]
https://github.com/luckyframework/avram/blob/e638ffb8eb5e8088449dfa63cb61a0739212f38d/src/avram/save_operation_template.cr#L15-L22

The migrator will set the default UUID value to `gen_random_uuid()` now. This means we can remove it from the crystal side which will fix the issue of `new_record?` always returning false when using UUID.

Ref: https://github.com/luckyframework/avram/issues/393

**Comment by matthewmcgarvey** [comment]
Connected to https://github.com/luckyframework/avram/pull/578

Just adding it to say that it wasn't removed when the database generation was added for any particular reason. Should be just fine to take out 👍
