### ISSUE TITLE
Add the operation name to the unpermittable column error

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#719]
https://github.com/luckyframework/avram/blob/8f6301c169f8ca80b65a08de7f60a00d11cc791e/src/avram/save_operation.cr#L263

This error doesn't really tell you *which* model is missing "title", or which operation you're trying to permit this column in. Specifically in Avram, this requires a lot of digging around. It seems we can use `@type` to at least get the operation name and that at least narrows it down a bit.

We could update this error to:

```diff
- Error: Can't permit 'title' because the column has not been defined on the model.
+ Error: Can't permit 'title' because the column has not been defined on the model for #{@type}.
```

**Comment by RhnSharma** [comment]
I would like to take this one.
