### ISSUE TITLE
Migrations increase compile time

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#730]
There might not be much we can do about this since It's probably more of a Crystal specific issues; however, I recently confirmed that the more migration files you have, the longer it takes to compile your app.

Related: https://github.com/luckyframework/avram/issues/729#issuecomment-918335679

Also, this could be a place to start investigating https://github.com/crystal-lang/crystal/pull/11197

**Comment by robacarp** [comment]
Right now the migration code is always compiled into the whole app, but I don't think it needs to be. In most executions the migration code will never be run. What if the migrations aren't compiled into the binary, but are each executed individually with a subprocess of `crystal run`?

The `lucky db.migrate` command would then:

- check the filenames against the database
- make a list of migrations which need to be run
- run each of them in subprocess `crystal run db/migrations/nnnnnnnnnnnnnn_add_column_to_table`

**Comment by jwoertink** [comment]
The migrations are actually required to boot an app https://github.com/luckyframework/lucky_cli/issues/675 I also found this out because my app does this for production. I removed the migrations from my app, then it stopped running migrations in production :sweat_smile:

**Comment by robacarp** [comment]
Right! This would need to change as well. Currently they're required because that's how the decision about "is the app migrated?" is made -- but it doesn't have to be that way. If the decision was instead made by filesystem inspection rather than [stashing classes](https://github.com/luckyframework/avram/blob/master/src/avram/migrator/migration.cr#L10) in [an array](https://github.com/luckyframework/avram/blob/master/src/avram/migrator/runner.cr#L11), that requirement wouldn't be present anymore.

**Comment by robacarp** [comment]
Moreover, the crystal community is generally aware of compile time problems. There aren't yet big sufficient solutions to that problem, but it's not a _lucky_ problem. Sure maybe we can improve by changing the way migrations are run (interpreted, perhaps?), but that's only going to defer the larger problem of "big projects take time to compile".

**Comment by jwoertink** [comment]
I'm going to close this as I've found no significant data to prove this claim. I've started a new Lucky project and the number of migrations hasn't seem to increase compile time significantly like it did on my other. Also, with all the focus in the community on this being an issue in Crystal, I'm not sure there's anything we can really do here.
