### ISSUE TITLE
Provide an easier way to translate validations

### ISSUE THREAD

**Issue by wout** [luckyframework/avram#754]
As it is currently, validation error messages are hardcoded. The only way to translate them is through the `message` argument, which results in a lot of repetition:

```cr
validate_required email,
  message: r("lucky.validate.required").t
validate_uniqueness_of email,
  message: r("lucky.validate.uniqueness").t
validate_format_of email,
  with: /[^@]+@[^\.]+\..+/,
  message: r("lucky.validate.email_format").t
validate_required first_name,
  message: r("lucky.validate.required").t
validate_required last_name,
  message: r("lucky.validate.required").t
validate_inclusion_of language,
  in: Rosetta.available_locales.map(&.to_s),
  message: r("lucky.validate.inclusion").t
validate_inclusion_of theme,
  in: User::Theme.values,
  message: r("lucky.validate.inclusion").t
```

How about creating an adapter to allow i18n libraries to hook into and overwrite Avram's default values? It could be a simple as:

```cr
module Avram::I18nBackend
  macro get(key)
    {
       validate_required: "is required",
       validate_uniqueness_of: "is already taken",
       # ...
    }[{{key.id}}]
  end
end
```

And then allow the backend to be configured:

```cr
Avram.configure do |settings|
  settings.i18n_backend = Rosetta::LuckyI18nBackend
end
```

The above is all untested and from the top of my head. I'm open to suggestions. What do you guys think?

**Comment by jwoertink** [comment]
I believe this is done now via #757 I'm going to close this, but if there's still more to do, we can re-open it.

**Comment by wout** [comment]
Yes, that one is done. Still working on this, though: https://github.com/luckyframework/lucky/discussions/1773.
