### ISSUE TITLE
Add random_order query method

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#755]
If you want your results to come back in a random order, you can currently do

```
UserQuery.new.order_by("RANDOM()", :asc)
```

But it would be neat if it was just built in with `UserQuery.new.random_order`.

**Comment by wout** [comment]
I'll take care of this!

**Comment by jwoertink** [comment]
Sweet!

**Comment by jwoertink** [comment]
Closed by https://github.com/luckyframework/avram/pull/765
