### ISSUE TITLE
Naming your model Status causes named collisions

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#758]
https://github.com/luckyframework/avram/blob/76e34c0e46d984c037eae9c8607514dc0b51eeec/src/avram/save_operation.cr#L26

https://github.com/luckyframework/avram/blob/76e34c0e46d984c037eae9c8607514dc0b51eeec/src/avram/delete_operation.cr#L18

If you have a model named `Status`, we will generate `SaveStatus` and `DeleteStatus` operations, but since those also exist as enums, Crystal will throw some errors.

We should just rename these enums since they're used internally anyway. Maybe `SaveOperationStatus` and `DeleteOperationStatus`... I think there's a less likely chance you'll name a model "OperationStatus"... or maybe we just call it `OperationStatus` on both? 🤔

**Comment by robacarp** [comment]
I have hit this bug myself and it's a real pain. Perhaps they could be `AvramSaveStatus` or `Avram::SaveStatus` etc to decrease the chance of global namespace collisions.
