### ISSUE TITLE
Adding the byte array data type

### ISSUE THREAD

**Issue by wout** [luckyframework/avram#762]
An app I'm building is using two databases. The first one is an internal database for authentication and aggregated data. The other is provided by [cardano-db-sync](https://github.com/input-output-hk/cardano-db-sync), which is a component that syncs the Cardano blockchain into a Postgres database.

In their schema, they're using the Postgres' `bytea` datatype to store block and transaction hashes. I've been able to make this work with Avram using the following modifications.

First, there's the adapter for `Bytes`, which is an alias of `Slice(UInt8)`:

```cr
struct Slice(T)
  def self.adapter
    Lucky
  end

  module Lucky
    alias ColumnType = Bytes
    include Avram::Type

    def self.criteria(query : T, column) forall T
      Criteria(T, Bytes).new(query, column)
    end

    def from_db!(value : Bytes)
      value
    end

    def parse(value : Bytes)
      SuccessfulCast(Bytes).new(value)
    end

    def to_db(value : Bytes)
      value
    end

    class Criteria(T, V) < String::Lucky::Criteria(T, V)
    end
  end
end
```
I'm not really familiar with the `Criteria` object in the adapter, so maybe I'm overlooking something there.

Next, there's this modification to allow querying with an instance of `Bytes`:

```cr
abstract class Avram::Where::ValueHoldingSqlClause < Avram::Where::SqlClause
  getter value : String | Array(String) | Array(Int32) | Slice(UInt8)
end
```

So now this works as expected:

```cr
class Cardano::Block < Cardano::BaseModel
  table :block do
    # ...
    column hash : Bytes
    # ...
  end
end
```

One thing I worry about is that the adapter is added specifically for `Slice(UInt8)`, but the type is `Slice(T)`. Not sure if that's going to cause trouble in the future, or not.

I'm wondering now, is it worthwhile adding this data type to Avram? In my case, I have a read-only database, so I'm good with the two modifications. If we were to add it as an officially supported type, this should also work with operations and migrations.

If you think it's a good addition, I'll gladly prepare a PR. 🤓️

**Comment by hugopl** [comment]
A PR for this would be awesome, since I'm also needing this and I'm using the first first code snippet to let avran read `bytea` columns too :sweat_smile: :rofl:

**Comment by jwoertink** [comment]
@hugopl PR started... I may need some extra eyes on this since I've never used `bytea` columns. I have no idea what all is needed, how to query them through raw SQL, or update existing records. I'll try to poke at it more when I have more time, but any suggestions you have are welcome.
