### ISSUE TITLE
Discussion: Clarify what 'fillable' means and give it a different name

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#77]
I think there is still some confusion about what `fillable` means. It means that fields are allowed to be filled by params. Params typically from an HTML form or from JSON provided to an API.

Instead people often think they need to add `fillable` to work with a field at all (even if you are setting a value in the form class), when in reality **all fields can be set within the form class**. 

The proposal is to find naming that makes this clearer.

```crystal
class SignUpForm < User::BaseForm
  allow_params name, email
end
```

Other alternatives:

* ~`user_fillable name, email`~ https://github.com/luckyframework/avram/issues/77#issuecomment-478631331
* ~`whitelist_params name, email`~ too verbose
* `permitted name, email` (kind of like Rails strong params)
* `permit_params name, email` I like this more than ^ because it mentions params which is the thing we are permitting

Thoughts?

**Comment by jwoertink** [comment]
That feels a bit more verbose. I also wonder if that would confuse people that might think it's model related like mistaking it with `admin_fillable` under `Admin::BaseForm` or whatever... 

I know it's used already, but would this be a good spot for `exposed` ?

**Comment by paulcsmith** [comment]
Yeah good point. Especially since the "user" may be a client calling a JSON API or something, not necessarily a `User`. I think `exposed` might be confusing since it doesn't expose extra data.

Maybe one of these could work?

* `whitelist name, email`
* `permitted name, email` (kind of like Rails strong params)

**Comment by paulcsmith** [comment]
The other problem with "fillable" is people think that you need to add "fillable" to use a field at all, even within the form class. In reality all fields are fillable in the form class. "fillable" just means it allows them to be set by the params

**Comment by jwoertink** [comment]
I like the `permitted`.

**Comment by paulcsmith** [comment]
I’d love to hear your thoughts on this @edwardloveall @HarrisonB @hanneskaeufler 

I’m leaning toward allow_params or permit_params.

**Comment by edwardloveall** [comment]
What about `inputs`? That implies that it's coming from outside as opposed to being set from within. Maybe it's a little generic?

**Comment by paulcsmith** [comment]
Yeah I think `input` might be a bit too generic. Technically input could also come from within the form class or somewhere other than params. Whereas this applies just to params and not other types of inputs

**Comment by HarrisonB** [comment]
I like `permit`,`permitted`, or `permit_param`.

**Comment by ditsara** [comment]
My thoughts (Rails background):

- I don't particularly mind `fillable` -- it's another (small) difference to learn coming from Rails, but the macro name does make some sense
- `permit` would be nice because it's exactly the syntax for Rails strong params

Could we overcome any confusion by simply including some comments in the generated Form? ie:

```crystal
class UserForm < User::BaseForm
  # Edit and uncomment to allow user input (via form or API)
  # fillable <all the fields in User>
end
```

**Comment by edwardloveall** [comment]
I like `permit` also, but I don't think it's clear enough. In rails, you call `params.permit(...` which makes it clear that you're permitting params specifically. `permit_params` or `permitted_params` is probably the best we've come up with so far.

**Comment by paulcsmith** [comment]
Thank you for the suggestions. @ditsara  I like the idea of adding a comment. I think it would still be useful to also change the name because someone may delete the comment early on in the project so later devs won't see it.

I like that some version of "permit" is familiar to Rails devs (as mentioned by everyone), and I like @edwardloveall's point about Rails making it clear it is for params since you call it on the params object.

My thought is `permit` > `permitted` because it makers as much sense but is shorter and easier to spell. So I'm 99% sure we'll go with `permit_params`.

**Comment by hanneskaeufler** [comment]
I kind of liked `fillable` because `params` is suuch an often used term in many different contexts. `fillable_by_params` maybe? `permit_params` feels fair enough as well.
