### ISSUE TITLE
Group+Aggregate Queries on Models

### ISSUE THREAD

**Issue by grepsedawk** [luckyframework/avram#777]
It would be really cool to have the Analog to `Model.group(:name).count` functionality

It was mentioned something like this isn't really possible for the typing. It is a little awkward either way, but here is the way I ended up solving this (without the API in avram):

```crystal
class ModelCount
  DB.mapping({
    name: String,
    count: Int64
  })
 end

query = <<-SQL
            SELECT name, COUNT(*)
            FROM models
            GROUP BY name
            ORDER BY COUNT(*) desc
          SQL

AppDatabase.query_all(query, as: ModelCount)
```

**Comment by grepsedawk** [comment]
I think for this "count classes", I wonder if there's a way for use to generate this class on fly similar to ModelCount,. Maybe a macro would be a good fit here, but maybe there is a better approach that might work here that we can think of...

Then `select_count` or maybe some other name might be able to somehow return this class

**Comment by matthewmcgarvey** [comment]
For what it's worth, you can make this a more pleasant API by hiding this in your query object, I think (I haven't actually tested it).

```crystal
class ModelQuery < Model::BaseQuery
  def self.name_count : Hash(String, Int64)
    query = <<~SQL
      SELECT name, COUNT(*)
      FROM models
      GROUP BY name
      ORDER BY COUNT(*) desc;
    SQL
    new.database.query_all(query, as: {String, Int64}).to_h
  end
end
```

**Comment by grepsedawk** [comment]
Close, `as: {String, Int64}` returns an array of tuples

**Comment by matthewmcgarvey** [comment]
`[{"bob", 45}].to_h` becomes `{"bob" => 45}` I believe

**Comment by grepsedawk** [comment]
Perfect, that's super helpful and should be very helpful to solving this issue as well!
Thank you!
