### ISSUE TITLE
Automatically generate migrations based on model table definition

### ISSUE THREAD

**Issue by grepsedawk** [luckyframework/avram#781]
In the model, we define the columns with their types:

```crystal
class User < BaseModel
  table do
    column email : String
    column dont_need : String
    column encrypted_password : String
  end
end
```

Assuming this is the fully migrated copy of user, we could add a column:

```patch
class User < BaseModel
  table do
    column email : String
+   column doesnt_exist : String
-   column dont_need : String
  end
end
```

Then run something similar to `lucky please_generate_my_migrations_automatically` which would generate a migration to add the `doesnt_exist` column and drop the `dont_need` column.

**Comment by jwoertink** [comment]
Related: https://github.com/luckyframework/avram/issues/203

**Comment by grepsedawk** [comment]
Oh actually that covers this entire request, but much more fully.
This can be closed (feel free to re-open)
