### ISSUE TITLE
RFC: Migration Watcher for Procfile.dev (or standalone)

### ISSUE THREAD

**Issue by grepsedawk** [luckyframework/avram#794]
# Abstract

Provide a migration watcher to watch and run migrations to optimize and automate common developer tasks

I'm not sure this is a good idea, but I think it might be worth exploring

# Problem Statement

This RFC strives to solve 2 core workflow optimizations:

1. Sometimes in development, the dev database might be missing migrations due to new code introduced from updating current HEAD
2. In development, when working on migrations, you often need to rework and add stuff to migrations -- migrations can be re-run with `lucky db.rollback and && lucky db.migrate`

# Suggested Feature Addition

Add a `lucky db.migrate.watch` cli command that will:

1. Watch migration files/schema state - when schema is out of date, migrate
2. When a migration file changes, automatically `lucky db.rollback and && lucky db.migrate`

**Comment by robacarp** [comment]
> Sometimes in development, the dev database might be missing migrations due to new code introduced from updating current HEAD

This is a terribly tricky problem. Auto-migrating forward is easy, but auto-migrating backward is not.

**Comment by matthewmcgarvey** [comment]
This falls outside the scope of what we'd like to provide in Avram. Someone can definitely do it if they like, but it would be a separate shard. Going to close this to keep try to limit the amount of open issues.
