### ISSUE TITLE
Remove Bool return type signature from Avram#transaction

### ISSUE THREAD

**Issue by BrucePerens** [luckyframework/avram#796]
Currently, `Avram#transaction` enforces that the return value is `Bool`. This is historical and no longer necessary. It should instead return whatever the block returns.

Consider:

```
my_record = db.transaction do
  ...
  MyRecordType.create!(...)
end
```

vs.

```
my_record = nil
db.transaction do
  ...
  my_record = MyRecordType.create!(...)
end
```

The second form leaves us with an unwanted type union of `Nil` and `MyRecordType`. The first just gives us the wanted type.

**Comment by matthewmcgarvey** [comment]
It wouldn't return a `MyRecordType` in the case that the transaction is rolled back, though.

You might look at https://github.com/luckyframework/avram/issues/796 and the connected, closed PR

**Comment by BrucePerens** [comment]
> You might look at #796 and the connected, closed PR

Sorry, Wrong Number.

**Comment by BrucePerens** [comment]
Closing this, although I am still interested in where Matthew meant to point me to. I ended up writing Object#not_rollback! to decorate the return value of the transaction and do what I want.

**Comment by matthewmcgarvey** [comment]
Woops! https://github.com/crystal-lang/crystal-db/issues/145
