### ISSUE TITLE
Change logic on some validations to only validate if field is not blank

### ISSUE THREAD

**Issue by jmufugi** [luckyframework/avram#8]
I suggest some validations such as validate_size_of, validate_inclusion_of, and perhaps others, only kick in when field is filled, not when blank. 
As of now, for example, if is set ```validate_size_of name min: 3``` I get "Can't be too short" error even when field is blank. It seems to take on role of validate_required. Not required behavior especially for optional fields.

**Comment by paulcsmith** [comment]
Fixed by #299 :D
