### ISSUE TITLE
Can't change column to nilable

### ISSUE THREAD

**Issue by matthewmcgarvey** [luckyframework/avram#809]
I needed to make an Int64 column nilable, so I did `change_type leader_id : Int64?` and got this error which is really confusing

<img width="674" alt="Screen Shot 2022-02-03 at 4 39 02 PM" src="https://user-images.githubusercontent.com/17329408/152441165-c1dc9cd4-c027-415c-8a05-23203172c8a1.png">

It seems that we have no built in support for making columns nilable.

**Comment by jwoertink** [comment]
You'd use `make_optional` for this

https://github.com/luckyframework/avram/blob/58de41759bb71b7ae9f5fae3a82505e759a2387f/src/avram/migrator/statement_helpers.cr#L51-L53

```crystal
make_optional :groups, :leader
```

**Comment by matthewmcgarvey** [comment]
Should this still handle optional types, though?

Good find, though! I see that it is not documented on the website and there is a small reference to `make_required`

**Comment by jwoertink** [comment]
hmm... I'm on the fence between either have it handle that case, or have it raise compile-time error telling you to use `make_optional / required`.... Not sure that we really need both? We definitely need to document those on the site though.

**Comment by matthewmcgarvey** [comment]
There's two reasons why I think this method should support it,
- Right now the error is really bad
- In order to go from `String?` to `UUID?` you'd have to make it required, change the type, then make it optionally which is definitely not do-able at all

**Comment by jwoertink** [comment]
Those are both good enough reasons for me! I'm sold. :+1:
