### ISSUE TITLE
Slugify doesn't allow you to update the slug

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#813]
https://github.com/luckyframework/avram/blob/9251a965372d319977558bcbe3d0696f60aeb45e/src/avram/slugify.cr#L38

Not sure if this was intentional or not... I can see there being some issues where a slug could potentially clash.

In my case, sometimes users will mistype their username during signup. We don't allow them to change it, but if they request a fix, we can manually update it for them. In that instance, we would want to make sure the slug matches. It's pretty confusing when you add in the slugify, and nothing happens... no errors, nothing. It just doesn't update because the `slug.value` is not blank here. I'd even be ok with an error saying slug is already filled or something. Then you could at least `slug.value = nil` before hand.

**Comment by jwoertink** [comment]
This is a tough one. Taking a look at the spec for this:

https://github.com/luckyframework/avram/blob/9251a965372d319977558bcbe3d0696f60aeb45e/spec/avram/slugify_spec.cr#L5

we can see that it was intentional. I feel this is wrong though because if give you no output on if this is wrong. If you need to update the attribute used to create the slug, then you probably also want the slug to reflect that. Right now it just ignores you. But the question is, should we do a `Slugify.set!()` method that will raise an exception when the value is already set, or do we add `slug.add_error` and have the operation fail?

Would love to get your input @matthewmcgarvey

**Comment by matthewmcgarvey** [comment]
I do think we should change the API for this functionality. It should be on the user to know when to run this code. That being said, I do not think we should break existing users. So I would not want to change `Avram::Slugify.set`.

I think we could add `Avram::Slugify.generate` and have it not take in the attribute, but return a string.

```crystal
before_save do
  if name.changed?
    slug.value = Avram::Slugify.generate(using: [name], query: UserQuery.new)
  end
end
```
Does that make sense?

**Comment by jwoertink** [comment]
I like that :+1:
