### ISSUE TITLE
Maybe operations can have a param builder?

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#838]
While working on the SecTester https://github.com/luckyframework/lucky_sec_tester/issues/19 I thought about this...

What if operations had a `build_params` method or something... This could just take in a raw hash, and then create what it expects the params to be with the proper param keys and whatever else.

There's a few tricky things to think about here. It's already weird that an ORM has knowledge of HTTP params, so there has been talk about moving all of this logic over to Lucky directly. Then, say we did add it, what would it return? The SecTester wants a String, but the operations don't. By the time the params hit the operations, they've already been parsed and converted to `Avram::Paramable`.

This may or may not get added in, but I at least wanted to jot down some notes.

**Comment by robacarp** [comment]
@jwoertink Can you give some examples of inputs and outputs? I'm not sure I understand what you mean.

**Comment by jwoertink** [comment]
Sure!

This works from an Action because we have an `Avram::Paramable` (Lucky::Params)

```crystal
SignUpUser.create!(params)
```

But it doesn't work from a spec. It also doesn't work if say you're using GraphQL unless you always pass `params` all over the place since the bulk of logic happens in other classes and such.

It's a half-baked idea, but my initial thought was something like:

```crystal
params = SignUpUser.build_params({email: "test@test.com", password: "secret", password_confirmation: "secret"})
SignUpUser.create!(params)
```

You can actually sort of do this already.... though, it's more of a "loophole" than anything.

```crystal
params = Avram::Params.new({"email" => "test@test.com", "password" => "secret", "password_confirmation" => "secret"})
SignUpUser.create!(params)
```

The `Avram::Params` was actually intended for internal testing with Avram since you don't have access to Lucky (yet).

With that said, the whole concept of the params has been discussed tons of times with the idea of changing how they're built. Ref: https://github.com/luckyframework/lucky/pull/1519 Nothing is 100% locked in, but it's possible that whatever we end up deciding could make this whole issue irrelevant :man_shrugging:

**Comment by robacarp** [comment]
I know the "limit operations so you can't pass in a hash as params" is a feature, but it sounds like that's the wall you're bumping up against. The loophole you have there is the designated workaround for that compile-time guard, I think?

**Comment by jwoertink** [comment]
I'm gonna close this because as I did the array param stuff, I realized that `Avram::Params` isn't actually a loophole. It's an escape hatch that's intentional. Maybe this could be opened up again later, but for now it's not necessary.
