### ISSUE TITLE
Add a `grouped_checkbox` input for array support

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#851]
I have a working example here:

https://github.com/luckyframework/example_forms/blob/c00f2558d41e8b6ab3fd41018cdf4cf7417671ae/src/components/neighborhoods/form_fields.cr#L15-L22

This just needs to be turned in to something a bit easier to use. I was thinking maybe

```crystal
grouped_checkbox(operation.amenities, "Pool")
```

https://github.com/luckyframework/avram/blob/5c553aa7bd67a8ec8f00050eddda8adcdd0a72f8/src/lucky/ext/input_helpers.cr#L60

We have something similar for `<select>` inputs 
https://github.com/luckyframework/avram/blob/5c553aa7bd67a8ec8f00050eddda8adcdd0a72f8/src/lucky/ext/select_helpers.cr#L8-L12

I think the one thing I'm unsure of is, would this checkbox need to generate 2 like it does currently? I believe the current one does it in order to do Bool values so unchecked is sent over as a `false` value. My guess is, unless you had a `Array(Bool)`, then this wouldn't matter? I guess the other thing is how does the label work? Maybe it doesn't....

**Comment by robacarp** [comment]
I think it would need to generate one hidden input with the default value of the field, right?
