### ISSUE TITLE
Using upsert to change a nilable column value to nil doesn't seem to work

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#864]
If you have a SaveOperation using `upsert`, and one of the lookup columns is nilable, it doesn't seem to allow you to update that field to `nil`.

**Comment by jwoertink** [comment]
This also fails if you just want to update a non-lookup column to `nil`.

**Comment by franciscoGPS** [comment]
Friendly reminde  today you forgot this was an actual open issue :stuck_out_tongue_closed_eyes:
