### ISSUE TITLE
Allow disabling default columns

### ISSUE THREAD

**Issue by lesderid** [luckyframework/avram#87]
It should be possible to disable default columns (`id`, `created_at`, and `updated_at`), both in the migrations and the models.

As a reference, the way Laravel does this is:
* adding id and timestamps to a table in a migration is explicit (but included by default in an `artisan`-generated migration),
* disabling timestamps in the model is possible through a field (`public $timestamps = false;`),
* changing/deleting the primary key in the model is also possible through a field (`protected $primaryKey = "column_name"`/`null;`).

Related: https://github.com/luckyframework/avram/issues/6

**Comment by paulcsmith** [comment]
I totally agree it should be optional. I’m trying to get more information on the use case and how important it is though so I can prioritize it. Right now I am prioritizing some changes to how records are saved and doing some internal refactoring.  But maybe this is a bigger deal than that. 

Thanks for the comment and examples. That always helps!

**Comment by paulcsmith** [comment]
BTW the API I had in mind for this is:

```
# migrations
create :my_table, timestamps: false, primary_key: false do/end

# models
table :my_table, timestamps: false, primary_key: false do/end
```

**Comment by wuzhonglin** [comment]
When I run lucky under PG, it said "PG::ResultSet#read returned a Int64. A Int32 was expected."
It looked like lucky think the primary key id is int32, but the actually pg return int64, is it possible to change the primary data type in config/database.cr? or disable autogenerate columns?

**Comment by paulcsmith** [comment]
@wuzhonglin Right now the id type is Int32 and no way to change it, but we will be changing that to default to Int64 soon.

There are a couple places this needs to change and should be relatively easy if you want to take a stab at it:

* https://github.com/luckyframework/avram/blob/08016336b47c0f175a0e396e9b923f3483731967/src/avram/migrator/primary_key_type.cr#L3
* https://github.com/luckyframework/avram/blob/08016336b47c0f175a0e396e9b923f3483731967/src/avram/model.cr#L26

If not I plan to get to this soon!

**Comment by wuzhonglin** [comment]
thank you for your answer
