### ISSUE TITLE
Default primary key to Int64 instead of Int32

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/avram#89]
https://github.com/luckyframework/avram/issues/87#issuecomment-497837244

**Comment by jwoertink** [comment]
Just to add to this, right now the tables created generate a `SERIAL` for Int32. With Int64, they should generate `BIGSERIAL`. This should also be configurable to use either (as well as other types), but still default to Int64.

**Comment by paulcsmith** [comment]
Good point! BTW could you try this out? I'm curious if setting Int64 to default will still work with old Int32 columns. 

The reason I ask is I wonder if we can safely change the default types in Crystal to Int64 and still work with old columns created as Int32. I *think* it should work, in which case this will be super easy to make the default. I just haven't had time to try this out

**Comment by jwoertink** [comment]
Yup. I'll give that a shot and report back.

**Comment by jwoertink** [comment]
There's quite a few spots that mention `Int32`. I tried to change the ones I thought were relevant to `Int64`, but  it seems PG didn't like that:

```
icr(0.28.0) > u = UserQuery.new.first
Unhandled exception: PG::ResultSet#read returned a Int32. A Int64 was expected. (Exception)
  from PG::ResultSet@DB::ResultSet#read<Int64.class>:Int64
  from User#initialize<PG::ResultSet>:Int32
  from User::new<PG::ResultSet>:User
  from User::from_rs<PG::ResultSet>:Array(User)
  from UserQuery@Avram::Queryable(T)#exec_query:Array(User)
  from UserQuery@Avram::Queryable(T)#results:Array(User)
  from UserQuery@Avram::Queryable(T)#first?:(User | Nil)
  from UserQuery@Avram::Queryable(T)#first:User
  from __icr_exec__:User
  from __crystal_main
  from Crystal::main_user_code<Int32, Pointer(Pointer(UInt8))>:Nil
  from Crystal::main<Int32, Pointer(Pointer(UInt8))>:Int32
  from main
```

I think adding in the BIGSERIAL as Int64 may still work without borking current setup DBs. My guess is PG would see SERIAL, and maybe the crystal-db would know to map this to Int32 where if it saw BIGSERIAL, it could map to Int64.

**Comment by paulcsmith** [comment]
Yeah maybe that could work. Another alternative would be to build in a method or figure out some SQL so people can easily switch to Int64/bigserial.
