### ISSUE TITLE
Compile error for optional association preloads

### ISSUE THREAD

**Issue by akadusei** [luckyframework/avram#922]
I'm getting a compile error when preloading optional associations. It seems to originate from here:

https://github.com/luckyframework/avram/blob/6d5357eca70f63150e740f7ac6f3473a0c33da37/src/avram/associations/belongs_to.cr#L64

```
Error: 

The 'eq' method can't compare a column to a value that may be 'nil'.
# ...
```

It seems the `#eq` method does not accept nilable arguments.

**Comment by jwoertink** [comment]
This is correct, the `eq` method doesn't allow for nilable arguments. You'd have to use [nilable_eq](https://github.com/luckyframework/avram/blob/6d5357eca70f63150e740f7ac6f3473a0c33da37/src/avram/criteria.cr#L91) in that case... but I guess the bigger question is why are you getting this error? Or... why has this not come up until now? :joy:  I have a few nilable associations in my apps that get preloaded, so it would seem that either this code should work, or it should have thrown this error quite a while ago. Very strange :thinking:

**Comment by matthewmcgarvey** [comment]
This bug was introduced in https://github.com/luckyframework/avram/commit/285a90264069250f1c33edb257d79470ddef1b57 which is really new and I think only affects preloading in the new way (with an existing record).

**Comment by akadusei** [comment]
> You'd have to use [nilable_eq](https://github.com/luckyframework/avram/blob/6d5357eca70f63150e740f7ac6f3473a0c33da37/src/avram/criteria.cr#L91) in that case... but I guess the bigger question is why are you getting this error?

I got this error while testing [Shield](https://github.com/GrottoPress/shield) with the master branch of Avram. It's an existing code, calling `BearerLoginQuery.preload_oauth_client` which compiles OK with Avram v1.0.0-rc1.

> This bug was introduced in https://github.com/luckyframework/avram/commit/285a90264069250f1c33edb257d79470ddef1b57 which is really new and I think only affects preloading in the new way (with an existing record).

That's correct. The said line should probably check if the association is nil and call the appropriate method.

**Comment by jwoertink** [comment]
Ah! That explains it. Yeah, I haven't tested the main branch stuff :sweat_smile: Good find.
