### ISSUE TITLE
Investigate removing pg client requirement

### ISSUE THREAD

**Issue by jwoertink** [luckyframework/avram#926]
Many of the tasks require pg client tools to be installed like `db.create` just runs `createdb ...`, and `db.drop` runs `dropdb ...`... This is super convenient, and really easy to interface with. The downside is the require the install postgres client tools.

I'm pretty sure we can run all of these commands in straight SQL on the server, but I have no clue how. I've always used the client tools even before Lucky, so that's what I'm comfortable with. We will need to dive in to the code and find all the spots where CLI stuff is used. Including the stuff that uses `psql`. For example, how do you do a DB dump and DB restore from within raw SQL?

I really don't want to play the game of "as long as you don't use X, then you won't need client tools". If we can't make it an all or nothing, then I don't think it'll be worth the hassle.

**Comment by steve-bitdotio** [comment]
fwiw I believe dumping a postgres database without pg_dump is feasible but non trivial.

https://stackoverflow.com/questions/9433158/dumping-a-db-without-pg-dump

**Comment by jwoertink** [comment]
I guess another option could be if the dump and restore are the only ones that require client tools, those could be abstracted to a sort of "plugin".... Then core Avram wouldn't need client tools, but also wouldn't have those readily available. Then when you do need them, you'd just `require "avram/extras/pg_tools"` or whatever...
