### ISSUE TITLE
Enum array

### ISSUE THREAD

**Issue by notramo** [luckyframework/avram#940]
Is it possible to use an Enum array somehow? This doesn't work:
```crystal
enum MyEnum
  First
  Second
end

class MyModel < BaseModel
  table do
    column enum_array : Array(MyEnum)
  end
end

**Comment by jwoertink** [comment]
I don't think that's been built yet. You could probably do Array(Int32) then handle some mapping back and forth. I haven't needed this yet, so I'm not sure how to implement it.
