### ISSUE TITLE
Add new member to one-to-many relations

### ISSUE THREAD

**Issue by notramo** [luckyframework/avram#947]
Let's assume there is a `User` and a `Comment` model. A single user can have multiple comments. How to insert new comment so that it belongs to that user? Is it possible using relations, or do I have to set the user_id manually? Also, is it possible to link an existing comment to an user using relations?

**Comment by jwoertink** [comment]
You have to specify the user_id of the comment. Normally it would be something like

```crystal
class SaveComment < Comment::SaveOperation
  needs user : User
  before_save do
    user_id.value = user.id
  end
end

SaveComment.create!(user: current_user)
```

I think that would work for linking an existing comment to a user.

```crystal
SaveComment.update!(existing_comment, user: current_user)
```
