### ISSUE TITLE
Access non-fillable model properties

### ISSUE THREAD

**Issue by notramo** [luckyframework/avram#953]
How to access a property of a model that is not in `permitted_columns`, but have to change? E.g. a `Post` have a fillable`description` and a `last_edit_version`. When the permitted `description` changes, the `description.original_value` is saved to `last_edit_version`.

**Comment by jwoertink** [comment]
Permitted columns only allow being updated by `params`. You can still update all of the columns either by passing in that column as a named arg, or by assigning the `value` in a `before_save`.

```crystal
SavePost.update(post, params, last_edit_version: 1)

class SavePost < Post::SaveOperation
  before_save do
    last_edit_version.value = 1
  end
end
```

**Comment by notramo** [comment]
How to update a column that is not passed as argument, and only exists on the model?

**Comment by jwoertink** [comment]
You update it in your `before_save` like this

```crystal
class SavePost < Post::SaveOperation
  before_save do
    last_edit_version.value = 1
  end
end
```
